#pragma once
#include <string>
#include <cstdint>

std::string baseUrl;             // "base_url" key(const std::string& json);
std::string issuer;              // OIDC issuer URL(const std::string& json);
std::string accountUrl;          // account management URL(const std::string& json);
std::string integrationsJson;              // "m.integrations" key — raw JSON(const std::string& json);
std::string userId;              // "@user(const std::string& json);
std::string example.org"(const std::string& json);
std::string accessToken;         // "syt_..."(const std::string& json);
std::string refreshToken;        // optional(const std::string& json);
std::string homeServer;          // deprecated, extract from userId(const std::string& json);
std::string deviceId;            // "ABCDEFGH"(const std::string& json);
std::string homeServerUrl;           // user-entered homeserver URL(const std::string& json);
std::string homeServerUrlBase;       // actual API base URL (may differ after well-known redirect)(const std::string& json);
std::string identityServerUrl;       // optional(const std::string& json);
std::string antiVirusServerUrl;      // optional(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> allowedFingerprints; // TLS certificate fingerprints(const std::string& json);
std::string userId() const { return credentials.userId; }(const std::string& json);
std::string deviceId() const { return credentials.deviceId; }(const std::string& json);
std::string homeServerUrl() const { return homeServerConfig.homeServerUrl; }(const std::string& json);
std::string homeServerUrlBase() const { return homeServerConfig.homeServerUrlBase; }(const std::string& json);
std::string PresenceEnum presenceEnumFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string statusMessage;           // user-set status message(const std::string& json);
std::string threadSummarySenderInfoJson; // SenderInfo serialized(const std::string& json);
std::string threadSummaryLatestEventJson; // Event serialized(const std::string& json);
std::string lastRootThreadEdition;     // event ID of last root thread edit(const std::string& json);
std::string Credentials parseCredentials(const std::string& json);
std::string SessionParams parseSessionParams(const std::string& json);
std::string UserPresence parseUserPresence(const std::string& json);
std::string credentialsToJson(const Credentials& creds);(const std::string& json);
std::string sessionParamsToJson(const SessionParams& params);(const std::string& json);
std::string userPresenceToJson(const UserPresence& presence);(const std::string& json);
std::string algorithm;       // "m.pbkdf2"(const std::string& json);
std::string salt;            // base64(const std::string& json);
std::string algorithm;       // "m.secret_storage.v1.curve25519-aes-sha2"(const std::string& json);
std::string name;            // human-readable key name(const std::string& json);
std::string publicKey;       // base64(const std::string& json);
std::string ciphertext;      // unpadded base64(const std::string& json);
std::string mac;             // integrity check(const std::string& json);
std::string ephemeral;       // ephemeral key(const std::string& json);
std::string iv;              // initialization vector(const std::string& json);
std::string detail;          // secret name, key ID, algorithm name, etc.(const std::string& json);
std::string SecretStorageKeyContent parseSecretStorageKey(const std::string& json);
std::string EncryptedSecretContent parseEncryptedSecret(const std::string& json);
std::string KeyInfoResult parseKeyInfoResult(const std::string& json);
std::string issuer;                                      // OIDC issuer URL(const std::string& json);
std::string accountManagementUri;                        // external account management(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> accountManagementActions;       // supported actions(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> missingStages;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> completedStages;(const std::string& json);
std::string sessionJson;                                 // for SUCCESS — Session serialized(const std::string& json);
std::string homeServerUrl;                               // for PROMPT(const std::string& json);
std::string identityServerUrl;                           // for PROMPT(const std::string& json);
std::string errorMessage;                                // for FAIL_ERROR(const std::string& json);
std::string url;                                         // HTTP pusher URL(const std::string& json);
std::string format;                                      // "event_id_only"(const std::string& json);
std::string pushKey;(const std::string& json);
std::string kind;                                        // "http" or "email"(const std::string& json);
std::string appId;(const std::string& json);
std::string appDisplayName;(const std::string& json);
std::string deviceDisplayName;(const std::string& json);
std::string profileTag;(const std::string& json);
std::string lang;(const std::string& json);
std::string deviceId;(const std::string& json);
std::string humanReadableMessage;(const std::string& json);
std::string url;                                         // og(const std::string& json);
std::string url(const std::string& json);
std::string siteName;                                    // og(const std::string& json);
std::string site_name(const std::string& json);
std::string title;                                       // og(const std::string& json);
std::string title(const std::string& json);
std::string description;                                 // og(const std::string& json);
std::string description(const std::string& json);
std::string mxcUrl;                                      // og(const std::string& json);
std::string image(const std::string& json);
std::string eventId;(const std::string& json);
std::string senderInfoJson;                              // SenderInfo serialized(const std::string& json);
std::string annotationsJson;                             // EventAnnotationsSummary serialized(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> readReceiptIds;                 // read receipt event IDs(const std::string& json);
std::string roomId;(const std::string& json);
std::string version;(const std::string& json);
std::string preferred;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> support;(const std::string& json);
std::string defaultRoomVersion;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, RoomCapabilityInfo> capabilities;(const std::string& json);
std::string defaultIdentityServerUrl;(const std::string& json);
std::string externalAccountManagementUrl;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> externalAccountManagementActions;(const std::string& json);
std::string authenticationIssuer;(const std::string& json);
std::string RoomCapabilitySupport isFeatureSupported(const std(const std::string& json);
std::string string& feature) const;(const std::string& json);
std::string versionOverrideForFeature(const std(const std::string& json);
std::string string& feature) const;(const std::string& json);
std::string value;               // email address or phone number(const std::string& json);
std::string matrixId;(const std::string& json);
std::string creatorUserId;       // "creatorUserId" key(const std::string& json);
std::string id;                  // "id" key(const std::string& json);
std::string type;                // "type" key — e.g. "m.jitsi"(const std::string& json);
std::string url;                 // "url" key(const std::string& json);
std::string name;                // "name" key(const std::string& json);
std::string dataJson;            // "data" key — raw JSON(const std::string& json);
std::string eventJson;           // Event serialized(const std::string& json);
std::string widgetId;(const std::string& json);
std::string senderInfoJson;      // SenderInfo serialized(const std::string& json);
std::string widgetType;          // WidgetType string value(const std::string& json);
std::string HomeServerCapabilities parseHomeServerCapabilities(const std::string& json);
std::string WidgetContent parseWidgetContent(const std::string& json);
std::string roomId;(const std::string& json);
std::string RoomNotificationState state, const std(const std::string& json);
std::string string& roomId)(const std::string& json);
