#pragma once
#include <string>
#include <cstdint>

std::string sessionId;       // from /login or /register(const std::string& json);
std::string type;            // "m.login.password", "m.login.recaptcha", etc.(const std::string& json);
std::string params;          // additional params JSON(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> stages;  // remaining stages to complete(const std::string& json);
std::string sessionId;(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string AuthFlow parseAuthFlow(const std(const std::string& json);
std::string string& responseJson, int httpStatus);(const std::string& json);
std::string buildAuthStageBody(const std(const std::string& json);
std::string string& sessionId, const std(const std::string& json);
std::string string& type,(const std::string& json);
std::string const std(const std::string& json);
std::string string& paramsJson = "{}");(const std::string& json);
std::string bool requiresAdditionalAuth(const std(const std::string& json);
std::string string& responseJson, int httpStatus);(const std::string& json);
std::string parseAuthSessionId(const std(const std::string& json);
std::string string& responseJson);(const std::string& json);
std::string bool isAuthTypeSupported(const std(const std::string& json);
std::string string& type, const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& flows);(const std::string& json);
std::string getNextAuthStage(const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& completed,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& required);(const std::string& json);
std::string publicKey;(const std::string& json);
std::string siteKey;(const std::string& json);
std::string server;          // recaptcha server URL(const std::string& json);
std::string CaptchaInfo parseCaptchaInfo(const std(const std::string& json);
std::string string& responseJson);(const std::string& json);
std::string bool requiresCaptcha(const std(const std::string& json);
std::string string& responseJson);(const std::string& json);
std::string buildCaptchaResponse(const std(const std::string& json);
std::string string& sessionId, const std(const std::string& json);
std::string string& captchaToken);(const std::string& json);
std::string loginToken;(const std::string& json);
std::string TokenAuth parseTokenLogin(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string buildTokenLoginBody(const std(const std::string& json);
std::string string& token, const std(const std::string& json);
std::string string& deviceName = "");(const std::string& json);
std::string errorCode;       // "M_LIMIT_EXCEEDED"(const std::string& json);
std::string RateLimit parseRateLimit(const std(const std::string& json);
std::string string& responseJson, int httpStatus);(const std::string& json);
std::string formatRateLimitMessage(const RateLimit& limit);(const std::string& json);
