#pragma once
#include <string>
#include <cstdint>

std::string CallManagerCallState callManagerStateFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string CallManagerEndReason callManagerEndReasonFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string type;            // "offer" or "answer"(const std::string& json);
std::string sdp;             // Full SDP text(const std::string& json);
std::string sessionId;       // o= line session ID(const std::string& json);
std::string fingerprint;     // a=fingerprint line (DTLS)(const std::string& json);
std::string hash;            // fingerprint hash algorithm (sha-256)(const std::string& json);
std::string setup;           // a=setup(const std::string& json);
std::string (active/passive/actpass)(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> iceUfrag;   // a=ice-ufrag lines(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> icePwd;     // a=ice-pwd lines(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> candidates; // a=candidate lines(const std::string& json);
std::string SdpSession parseSdp(const std(const std::string& json);
std::string string& sdpText, const std(const std::string& json);
std::string string& type);(const std::string& json);
std::string sdpToJson(const SdpSession& sdp);(const std::string& json);
std::string sdpMid;          // Media stream ID(const std::string& json);
std::string candidate;       // Full candidate string(const std::string& json);
std::string foundation;      // 1st token(const std::string& json);
std::string foundation(const std::string& json);
std::string transport;       // "UDP" or "TCP"(const std::string& json);
std::string ip;(const std::string& json);
std::string type;            // "host", "srflx", "prflx", "relay"(const std::string& json);
std::string relayProtocol;   // "udp" or "tcp" (for relay)(const std::string& json);
std::string ParsedIceCandidate parseParsedIceCandidateLine(const std(const std::string& json);
std::string string& candidateLine, const std(const std::string& json);
std::string string& sdpMid, int sdpMLineIndex);(const std::string& json);
std::string callId;(const std::string& json);
std::string roomId;(const std::string& json);
std::string callerId;(const std::string& json);
std::string callerName;(const std::string& json);
std::string calleeId;        // Who we're calling (for outgoing)(const std::string& json);
std::string calleeName;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> participants;(const std::string& json);
std::string endReasonText;   // Human-readable reason(const std::string& json);
std::string roomName;        // For display(const std::string& json);
std::string CallEventType parseCallEventType(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string callId;(const std::string& json);
std::string senderId;(const std::string& json);
std::string senderName;(const std::string& json);
std::string contentJson;     // Raw event content(const std::string& json);
std::string title;           // "Alice is calling..."(const std::string& json);
std::string body;            // "Voice call" or "Video call"(const std::string& json);
std::string startOutgoingCall(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& calleeId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& calleeName, CallType type,(const std::string& json);
std::string const std(const std::string& json);
std::string string& sdpOffer, std(const std::string& json);
std::string string& error);(const std::string& json);
std::string handleIncomingCall(const std(const std::string& json);
std::string string& callId, const std(const std::string& json);
std::string string& roomId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& callerId, const std(const std::string& json);
std::string string& callerName,(const std::string& json);
std::string CallType type, const std(const std::string& json);
std::string string& sdpOffer,(const std::string& json);
std::string answerCall(const std(const std::string& json);
std::string string& callId, const std(const std::string& json);
std::string string& sdpAnswer, std(const std::string& json);
std::string string& error);(const std::string& json);
std::string rejectCall(const std(const std::string& json);
std::string string& callId, const std(const std::string& json);
std::string string& reason = "rejected");(const std::string& json);
std::string hangupCall(const std(const std::string& json);
std::string string& callId, CallManagerEndReason reason = CallManagerEndReason(const std::string& json);
std::string USER_HUNG_UP,(const std::string& json);
std::string const std(const std::string& json);
std::string string& reasonText = "");(const std::string& json);
std::string timeoutCall(const std(const std::string& json);
std::string string& callId);(const std::string& json);
std::string void addLocalParsedIceCandidate(const std(const std::string& json);
std::string string& callId, const ParsedIceCandidate& candidate);(const std::string& json);
std::string void addRemoteParsedIceCandidate(const std(const std::string& json);
std::string string& callId, const ParsedIceCandidate& candidate);(const std::string& json);
std::string buildCandidatesEvent(const std(const std::string& json);
std::string string& callId,(const std::string& json);
std::string std(const std::string& json);
std::string vector<ParsedIceCandidate> getRemoteCandidates(const std(const std::string& json);
std::string string& callId) const;(const std::string& json);
std::string void setCallConnected(const std(const std::string& json);
std::string string& callId);(const std::string& json);
std::string void setCallConnecting(const std(const std::string& json);
std::string string& callId);(const std::string& json);
std::string void setMuted(const std(const std::string& json);
std::string string& callId, bool muted);(const std::string& json);
std::string void setVideoEnabled(const std(const std::string& json);
std::string string& callId, bool enabled);(const std::string& json);
std::string void setRemoteVideo(const std(const std::string& json);
std::string string& callId, bool hasVideo);(const std::string& json);
std::string bool getCall(const std(const std::string& json);
std::string string& callId, CallSession& out) const;(const std::string& json);
std::string std(const std::string& json);
std::string vector<CallSession> getRoomCalls(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string bool isRoomInCall(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string int getCallDuration(const std(const std::string& json);
std::string string& callId) const;(const std::string& json);
std::string formatCallDuration(int seconds) const;(const std::string& json);
std::string callToJson(const CallSession& call) const;(const std::string& json);
std::string allCallsToJson() const;(const std::string& json);
std::string CallEvent parseCallEvent(const std(const std::string& json);
std::string string& eventType, const std(const std::string& json);
std::string string& contentJson,(const std::string& json);
std::string const std(const std::string& json);
std::string string& senderId, int64_t timestampMs);(const std::string& json);
std::string formatCallEvent(const CallEvent& event, const std(const std::string& json);
std::string string& senderDisplayName);(const std::string& json);
std::string CallSession* findCall(const std(const std::string& json);
std::string string& callId);(const std::string& json);
std::string const CallSession* findCall(const std(const std::string& json);
std::string string& callId) const;(const std::string& json);
std::string generateCallId() const;(const std::string& json);
