#pragma once
#include <string>
#include <cstdint>

std::string text;                 // Current composer text(const std::string& json);
std::string linkedEventId;        // For Quote/Edit/Reply — target event(const std::string& json);
std::string roomId;(const std::string& json);
std::string rootThreadEventId;    // null = not in thread(const std::string& json);
std::string text;                 // Current raw text(const std::string& json);
std::string TextFormat detectTextFormat(const std(const std::string& json);
std::string string& text);(const std::string& json);
std::string applyFormat(const std(const std::string& json);
std::string string& text, const TextFormat& format);(const std::string& json);
std::string stripFormatting(const std(const std::string& json);
std::string string& text);(const std::string& json);
std::string displayName;         // "Alice"(const std::string& json);
std::string userId;              // "@alice(const std::string& json);
std::string example.org"(const std::string& json);
std::string avatarUrl;           // mxc(const std::string& json);
std::string //...(const std::string& json);
std::string query;               // What the user typed after @(const std::string& json);
std::string bool isAtMentionTrigger(const std(const std::string& json);
std::string string& text, int cursorPos, bool& isRoom);(const std::string& json);
std::string extractMentionQuery(const std(const std::string& json);
std::string string& text, int cursorPos);(const std::string& json);
std::string buildMentionPill(const std(const std::string& json);
std::string string& displayName, const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string buildRoomMentionPill(const std(const std::string& json);
std::string string& roomAlias);(const std::string& json);
std::string replaceMention(const std(const std::string& json);
std::string string& text, const MentionMatch& match);(const std::string& json);
std::string shortcode;           // "(const std::string& json);
std::string smile(const std::string& json);
std::string "(const std::string& json);
std::string unicode;             // "😊"(const std::string& json);
std::string std(const std::string& json);
std::string vector<EmojiMatch> findEmojiShortcodes(const std(const std::string& json);
std::string string& text);(const std::string& json);
std::string replaceEmojiShortcode(const std(const std::string& json);
std::string string& text, const EmojiMatch& match);(const std::string& json);
std::string autoReplaceEmojis(const std(const std::string& json);
std::string string& text);(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string MessageValidation validateMessage(const std(const std::string& json);
std::string string& text, int maxLength = 65535);(const std::string& json);
std::string buildQuotedBody(const std(const std::string& json);
std::string string& quotedText, const std(const std::string& json);
std::string string& replyText,(const std::string& json);
std::string const std(const std::string& json);
std::string string& quotedSender = "");(const std::string& json);
std::string buildQuotedHtmlBody(const std(const std::string& json);
std::string string& quotedHtml, const std(const std::string& json);
std::string string& replyHtml,(const std::string& json);
std::string const std(const std::string& json);
std::string string& quotedSender = "");(const std::string& json);
std::string void enterEditMode(const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string void enterQuoteMode(const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string void enterReplyMode(const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string void setText(const std(const std::string& json);
std::string string& text);(const std::string& json);
std::string getText() const;(const std::string& json);
std::string insertMention(int cursorPos, const MentionMatch& match);(const std::string& json);
std::string applyBold(const std(const std::string& json);
std::string string& text, int selStart, int selEnd);(const std::string& json);
std::string applyItalic(const std(const std::string& json);
std::string string& text, int selStart, int selEnd);(const std::string& json);
std::string applyCode(const std(const std::string& json);
std::string string& text, int selStart, int selEnd);(const std::string& json);
std::string applyQuote(const std(const std::string& json);
std::string string& text, int selStart, int selEnd);(const std::string& json);
std::string stateToJson() const;(const std::string& json);
std::string sendModeToJson(const SendMode& mode) const;(const std::string& json);
std::string composerText_;(const std::string& json);
