#pragma once
#include <string>
#include <cstdint>

std::string resolveMxcDownloadUrl(const std(const std::string& json);
std::string string& mxcUrl, const std(const std::string& json);
std::string string& homeServerUrl);(const std::string& json);
std::string resolveMxcThumbnailUrl(const std(const std::string& json);
std::string string& mxcUrl, const std(const std::string& json);
std::string string& homeServerUrl,(const std::string& json);
std::string int width, int height, const std(const std::string& json);
std::string string& method = "scale");(const std::string& json);
std::string bool isMxcUri(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string extractMxcServerName(const std(const std::string& json);
std::string string& mxcUrl);(const std::string& json);
std::string extractMxcMediaId(const std(const std::string& json);
std::string string& mxcUrl);(const std::string& json);
std::string buildMxcUri(const std(const std::string& json);
std::string string& serverName, const std(const std::string& json);
std::string string& mediaId);(const std::string& json);
std::string body;              // m.text body, m.image caption, etc.(const std::string& json);
std::string format;            // "org.matrix.custom.html" for formatted text(const std::string& json);
std::string formattedBody;     // HTML body(const std::string& json);
std::string mxcUrl;            // m.image/m.video/m.audio/m.file URL(const std::string& json);
std::string thumbnailUrl;      // m.image thumbnail_info thumbnail_url(const std::string& json);
std::string filename;          // m.file filename(const std::string& json);
std::string mimetype;          // content-type of media(const std::string& json);
std::string geoUri;            // m.location geo_uri(const std::string& json);
std::string editEventId;       // event being edited(const std::string& json);
std::string replyEventId;      // event being replied to(const std::string& json);
std::string MessageType parseMessageType(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string MessageContent parseMessageContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string getMessageTypeLabel(MessageType type);(const std::string& json);
std::string getExtensionFromMimeType(const std(const std::string& json);
std::string string& mimetype);(const std::string& json);
std::string formatFileSize(int64_t bytes);(const std::string& json);
std::string messageContentToJson(const MessageContent& content);(const std::string& json);
std::string extractUsefulTextFromReply(const std(const std::string& json);
std::string string& repliedBody);(const std::string& json);
std::string extractUsefulTextFromHtmlReply(const std(const std::string& json);
std::string string& repliedHtmlBody, const std(const std::string& json);
std::string string& mxReplyStartTag = "<mx-reply>", const std(const std::string& json);
std::string string& mxReplyEndTag = "</mx-reply>");(const std::string& json);
std::string formatSpoilerTextFromHtml(const std(const std::string& json);
std::string string& formattedBody);(const std::string& json);
std::string buildTextWithImageContent((const std::string& json);
std::string const std(const std::string& json);
std::string string& plainText, const std(const std::string& json);
std::string string& imageMxcUrl,(const std::string& json);
std::string const std(const std::string& json);
std::string string& imageMimetype = "image/png",(const std::string& json);
std::string buildReplyWithImageContent((const std::string& json);
std::string const std(const std::string& json);
std::string string& plainText, const std(const std::string& json);
std::string string& imageMxcUrl,(const std::string& json);
std::string const std(const std::string& json);
std::string string& replyEventId, const std(const std::string& json);
std::string string& imageMimetype = "image/png");(const std::string& json);
std::string bool hasTextWithImage(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string ensureCorrectFormattedBodyInTextReply((const std::string& json);
std::string const std(const std::string& json);
std::string string& newFormattedBody,(const std::string& json);
std::string const std(const std::string& json);
std::string string& newBody,(const std::string& json);
std::string const std(const std::string& json);
std::string string& originalFormattedBody);(const std::string& json);
std::string normalizeMimeType(const std(const std::string& json);
std::string string& mimeType);(const std::string& json);
std::string bool isMimeTypeImage(const std(const std::string& json);
std::string string& mt);(const std::string& json);
std::string bool isMimeTypeVideo(const std(const std::string& json);
std::string string& mt);(const std::string& json);
std::string bool isMimeTypeAudio(const std(const std::string& json);
std::string string& mt);(const std::string& json);
std::string bool isMimeTypeText(const std(const std::string& json);
std::string string& mt);(const std::string& json);
std::string getLatestEditEventId(const std(const std::string& json);
std::string string& editSummaryJson, const std(const std::string& json);
std::string string& originalEventId);(const std::string& json);
std::string getEditedTargetEventId(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string getTextEditableContent(const std(const std::string& json);
std::string string& contentJson,(const std::string& json);
std::string const std(const std::string& json);
std::string string& editSummaryJson, bool formatted = false);(const std::string& json);
std::string bool isReplyEvent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool isEditionEvent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
