#pragma once
#include <string>
#include <cstdint>

std::string inline buildTextContent(const std(const std::string& json);
std::string string& msgType, const std(const std::string& json);
std::string string& body,(const std::string& json);
std::string const std(const std::string& json);
std::string string& formattedBody = "", const std(const std::string& json);
std::string string& format = "org.matrix.custom.html")(const std::string& json);
std::string json = R"({"msgtype"(const std::string& json);
std::string ")" + msgType + R"(","body"(const std::string& json);
std::string ")" + body + R"(")";(const std::string& json);
std::string inline buildImageContent(const std(const std::string& json);
std::string string& body, const std(const std::string& json);
std::string string& mxcUrl,(const std::string& json);
std::string int width = 0, int height = 0, int64_t size = 0, const std(const std::string& json);
std::string string& mimeType = "")(const std::string& json);
std::string json = R"({"msgtype"(const std::string& json);
std::string "m.image","body"(const std::string& json);
std::string ")" + body + R"(","url"(const std::string& json);
std::string ")" + mxcUrl + R"(")";(const std::string& json);
std::string inline buildFileContent(const std(const std::string& json);
std::string string& body, const std(const std::string& json);
std::string string& mxcUrl,(const std::string& json);
std::string const std(const std::string& json);
std::string string& fileName = "", int64_t size = 0, const std(const std::string& json);
std::string string& mimeType = "")(const std::string& json);
std::string json = R"({"msgtype"(const std::string& json);
std::string "m.file","body"(const std::string& json);
std::string ")" + body + R"(","url"(const std::string& json);
std::string ")" + mxcUrl + R"(")";(const std::string& json);
std::string inline buildLocationContent(const std(const std::string& json);
std::string string& body, const std(const std::string& json);
std::string string& geoUri)(const std::string& json);
std::string inline buildRoomNameContent(const std(const std::string& json);
std::string string& name) {(const std::string& json);
std::string inline buildRoomTopicContent(const std(const std::string& json);
std::string string& topic) {(const std::string& json);
std::string inline buildRoomAvatarContent(const std(const std::string& json);
std::string string& mxcUrl) {(const std::string& json);
std::string inline buildRoomMemberContent(const std(const std::string& json);
std::string string& membership,(const std::string& json);
std::string const std(const std::string& json);
std::string string& reason = "", const std(const std::string& json);
std::string string& displayName = "")(const std::string& json);
std::string json = R"({"membership"(const std::string& json);
std::string ")" + membership + R"(")";(const std::string& json);
std::string inline buildJoinRulesContent(const std(const std::string& json);
std::string string& rule,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& allowRoomIds = {})(const std::string& json);
std::string json = R"({"join_rule"(const std::string& json);
std::string ")" + rule + R"(")";(const std::string& json);
std::string inline buildGuestAccessContent(bool canJoin) {(const std::string& json);
std::string return R"({"guest_access"(const std::string& json);
std::string ")" + std(const std::string& json);
std::string string(canJoin ? "can_join"(const std::string& json);
std::string "forbidden") + R"("})";(const std::string& json);
std::string inline buildHistoryVisibilityContent(const std(const std::string& json);
std::string string& visibility) {(const std::string& json);
std::string inline buildPowerLevelsContent(int usersDefault, int eventsDefault, int stateDefault,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string pair<std(const std::string& json);
std::string string, int>>& userLevels = {})(const std::string& json);
std::string json = R"({"users_default"(const std::string& json);
std::string )" + std(const std::string& json);
std::string to_string(usersDefault) +(const std::string& json);
std::string inline buildEncryptionContent(const std(const std::string& json);
std::string string& algorithm = "m.megolm.v1.aes-sha2",(const std::string& json);
std::string inline buildTombstoneContent(const std(const std::string& json);
std::string string& body, const std(const std::string& json);
std::string string& replacementRoomId) {(const std::string& json);
std::string inline generateTransactionId() {(const std::string& json);
std::string inline buildPollStartContent(const std(const std::string& json);
std::string string& question,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& options, int maxSelections = 1)(const std::string& json);
std::string json = R"({"org.matrix.msc3381.poll.start"(const std::string& json);
std::string {"kind"(const std::string& json);
std::string "org.matrix.msc3381.poll.disclosed")";(const std::string& json);
std::string inline buildPollResponseContent(const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& selectedOptionIds) {(const std::string& json);
std::string json = R"({"org.matrix.msc3381.poll.response"(const std::string& json);
std::string {"answers"(const std::string& json);
std::string [)";(const std::string& json);
std::string inline buildPollEndContent(const std(const std::string& json);
std::string string& text = "Poll ended") {(const std::string& json);
