#pragma once
#include <string>
#include <cstdint>

std::string CSM_KeyUsage keyUsageFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string userId;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string> keys;      // "ed25519(const std::string& json);
std::string base64key" → base64key(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string>> signatures;(const std::string& json);
std::string getPublicKey() const;(const std::string& json);
std::string void addSignature(const std(const std::string& json);
std::string string& signerUserId, const std(const std::string& json);
std::string string& signedKey,(const std::string& json);
std::string const std(const std::string& json);
std::string string& signature);(const std::string& json);
std::string userId;(const std::string& json);
std::string publicKey;(const std::string& json);
std::string userId;(const std::string& json);
std::string keySigned;(const std::string& json);
std::string signature;(const std::string& json);
std::string Builder& key(const std(const std::string& json);
std::string string& pk) { publicKey = pk; return *this; }(const std::string& json);
std::string Builder& setUserId(const std(const std::string& json);
std::string string& uid) { this->userId = uid; return *this; }(const std::string& json);
std::string Builder& signature(const std(const std::string& json);
std::string string& uid, const std(const std::string& json);
std::string string& ks, const std(const std::string& json);
std::string string& sgn) {(const std::string& json);
std::string userId;(const std::string& json);
std::string error;(const std::string& json);
std::string deviceId;(const std::string& json);
std::string userId;(const std::string& json);
std::string masterKeyPrivate;       // MSK private(const std::string& json);
std::string selfSigningKeyPrivate;  // SSK private(const std::string& json);
std::string userSigningKeyPrivate;  // USK private(const std::string& json);
std::string void setUserKeys(const std(const std::string& json);
std::string string& userId, const CSM_CrossSigningInfo& info);(const std::string& json);
std::string CSM_CrossSigningInfo getUserKeys(const std(const std::string& json);
std::string string& userId) const;(const std::string& json);
std::string UserTrustResult importPrivateKeys(const std(const std::string& json);
std::string string& masterKeyPrivate,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userSigningKeyPrivate,(const std::string& json);
std::string const std(const std::string& json);
std::string string& selfSigningKeyPrivate);(const std::string& json);
std::string bool importPrivateKey(CSM_KeyUsage usage, const std(const std::string& json);
std::string string& privateKey);(const std::string& json);
std::string UserTrustResult checkUserTrust(const std(const std::string& json);
std::string string& otherUserId) const;(const std::string& json);
std::string DeviceTrustResult checkDeviceTrust(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& deviceId,(const std::string& json);
std::string void trustUser(const std(const std::string& json);
std::string string& otherUserId);(const std::string& json);
std::string void trustDevice(const std(const std::string& json);
std::string string& deviceId);(const std::string& json);
std::string static CSM_CrossSigningKey buildMasterKey(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& publicKey);(const std::string& json);
std::string static CSM_CrossSigningKey buildSelfSigningKey(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& publicKey);(const std::string& json);
std::string static CSM_CrossSigningKey buildUserSigningKey(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& publicKey);(const std::string& json);
std::string static CSM_CrossSigningInfo buildCrossSigningInfo(const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string crossSigningInfoToJson(const CSM_CrossSigningInfo& info) const;(const std::string& json);
std::string keyToJson(const CSM_CrossSigningKey& key) const;(const std::string& json);
std::string trustResultToJson(const UserTrustResult& result) const;(const std::string& json);
std::string deviceTrustToJson(const DeviceTrustResult& result) const;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, CSM_CrossSigningInfo> userKeys_; // userId → keys(const std::string& json);
