#pragma once
#include <string>
#include <cstdint>

std::string eventId;(const std::string& json);
std::string roomId;(const std::string& json);
std::string contentJson;            // encrypted content JSON(const std::string& json);
std::string timelineId;(const std::string& json);
std::string clearPayloadJson;       // {"type"(const std::string& json);
std::string "...","content"(const std::string& json);
std::string {...}}(const std::string& json);
std::string senderKey;(const std::string& json);
std::string errorCode;              // "M_UNKNOWN_SESSION", "M_BAD_MAC", etc.(const std::string& json);
std::string errorReason;(const std::string& json);
std::string sessionId;              // for retry-on-new-session tracking(const std::string& json);
std::string std(const std::string& json);
std::string unordered_set<std(const std::string& json);
std::string string> existingRequests;      // currently pending(const std::string& json);
std::string std(const std::string& json);
std::string unordered_set<std(const std::string& json);
std::string string> unknownSessionsFailure; // session IDs that failed(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>> sessionToEvents; // sessionId → eventIds(const std::string& json);
std::string inline std(const std::string& json);
std::string vector<DecryptionRequest> onNewSession(DecryptorState& state, const std(const std::string& json);
std::string string& sessionId) {(const std::string& json);
std::string userId;(const std::string& json);
std::string displayName;(const std::string& json);
std::string avatarUrl;(const std::string& json);
std::string inline resolveRoomAvatar((const std::string& json);
std::string const std(const std::string& json);
std::string string& roomAvatarUrl,         // from m.room.avatar state event(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& excludedUserIds,(const std::string& json);
std::string const std(const std::string& json);
std::string string& currentUserId)(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string pair<std(const std::string& json);
std::string string, bool>>& reactionsSummary, // {key, addedByMe}(const std::string& json);
std::string const std(const std::string& json);
std::string string& reaction)(const std::string& json);
std::string inline selectMemberContent((const std::string& json);
std::string const std(const std::string& json);
std::string string& content,           // "content" key from event(const std::string& json);
std::string const std(const std::string& json);
std::string string& prevContent,        // "prev_content" key from event(const std::string& json);
std::string const std(const std::string& json);
std::string string& eventType,(const std::string& json);
