#pragma once
#include <string>
#include <cstdint>

std::string eventId;(const std::string& json);
std::string serverName;      // matrix.org, server.com(const std::string& json);
std::string roomId;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> missingEventIds;(const std::string& json);
std::string missingServer;   // which server is missing events(const std::string& json);
std::string void trackEvent(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string string& serverName, int64_t timestamp);(const std::string& json);
std::string DesyncReport checkDesync(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& currentServer);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> getServers(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string void removeRoom(const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string bool hasEventOnServer(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string string& serverName) const;(const std::string& json);
std::string static formatDesyncWarning(const DesyncReport& report);(const std::string& json);
std::string static reportToJson(const DesyncReport& report);(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string unordered_set<std(const std::string& json);
std::string string>> serverEvents_;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int64_t> eventTimestamps_;(const std::string& json);
std::string reason;                  // human-readable explanation(const std::string& json);
std::string suggestedAction;         // "re-sync", "clear_cache", "re-login"(const std::string& json);
std::string const std(const std::string& json);
std::string string& roomId,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& localEventIds,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& serverEventIds,(const std::string& json);
std::string const std(const std::string& json);
std::string string& localReadMarker,(const std::string& json);
std::string const std(const std::string& json);
std::string string& serverReadMarker,(const std::string& json);
std::string const std(const std::string& json);
std::string string& localMembership,(const std::string& json);
std::string const std(const std::string& json);
std::string string& serverMembership(const std::string& json);
std::string getDesyncRecoveryAction(DesyncCause cause);(const std::string& json);
std::string getDesyncRecoveryAction(const DesyncCheckResult& result);(const std::string& json);
