#pragma once
#include <string>
#include <cstdint>

std::string deviceId;(const std::string& json);
std::string authType;            // "m.login.password" for UIA(const std::string& json);
std::string authSession;         // UIA session ID(const std::string& json);
std::string password;            // User password for UIA(const std::string& json);
std::string deviceId;(const std::string& json);
std::string newDisplayName;(const std::string& json);
std::string currentDeviceId;(const std::string& json);
std::string DevicesListResponse parseDevicesList(const std::string& json);
std::string DeviceInfo parseDeviceInfo(const std(const std::string& json);
std::string string& deviceId, const std(const std::string& json);
std::string string& json);(const std::string& json);
std::string CryptoDeviceInfo parseCryptoDeviceInfo(const std(const std::string& json);
std::string string& deviceId, const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& json);(const std::string& json);
std::string buildRenameRequest(const DeviceRenameRequest& req) const;(const std::string& json);
std::string buildDeleteRequest(const DeviceDeletionRequest& req) const;(const std::string& json);
std::string buildBatchDeleteRequest(const std(const std::string& json);
std::string vector<DeviceDeletionRequest>& requests) const;(const std::string& json);
std::string bool requiresUia(const std(const std::string& json);
std::string string& deleteResponseJson) const;(const std::string& json);
std::string formatTrustLevel(const DeviceVerification& level) const;(const std::string& json);
std::string getTrustLabel(const DeviceVerification& level) const;(const std::string& json);
std::string formatFingerprint(const std(const std::string& json);
std::string string& rawKey) const;(const std::string& json);
std::string formatShortKey(const std(const std::string& json);
std::string string& rawKey) const;(const std::string& json);
std::string formatLastSeen(int64_t lastSeenTs) const;(const std::string& json);
std::string bool satisfiesMinVersion(const std(const std::string& json);
std::string string& clientVersion, const std(const std::string& json);
std::string string& minRequired) const;(const std::string& json);
std::string deviceToJson(const DeviceInfo& device) const;(const std::string& json);
std::string cryptoDeviceToJson(const CryptoDeviceInfo& device) const;(const std::string& json);
std::string devicesToJson(const std(const std::string& json);
std::string vector<DeviceInfo>& devices) const;(const std::string& json);
std::string cryptoDevicesToJson(const std(const std::string& json);
std::string vector<CryptoDeviceInfo>& devices) const;(const std::string& json);
std::string trustLevelToJson(const DeviceVerification& level) const;(const std::string& json);
std::string static extractStr(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string static int64_t extractInt(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string static bool extractBool(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
