#pragma once
#include <string>
#include <cstdint>

std::string buildUserAgent((const std::string& json);
std::string const std(const std::string& json);
std::string string& appName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& appVersion,(const std::string& json);
std::string const std(const std::string& json);
std::string string& manufacturer,(const std::string& json);
std::string const std(const std::string& json);
std::string string& model,(const std::string& json);
std::string const std(const std::string& json);
std::string string& androidVersion,(const std::string& json);
std::string const std(const std::string& json);
std::string string& buildId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& flavorDescription,(const std::string& json);
std::string const std(const std::string& json);
std::string string& sdkVersion(const std::string& json);
std::string buildDeviceDisplayName(const std(const std::string& json);
std::string string& appName, const std(const std::string& json);
std::string string& deviceModel);(const std::string& json);
std::string bool isAsciiOnly(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string shortDeviceName(const std(const std::string& json);
std::string string& manufacturer, const std(const std::string& json);
std::string string& model);(const std::string& json);
std::string formatSdkVersion(const std(const std::string& json);
std::string string& sdkVersion);(const std::string& json);
std::string sanitizeUserAgentComponent(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string appName;(const std::string& json);
std::string appVersion;(const std::string& json);
std::string manufacturer;(const std::string& json);
std::string model;(const std::string& json);
std::string osName;        // "Android", "iOS", "Linux", "Windows", "macOS"(const std::string& json);
std::string osVersion;(const std::string& json);
std::string buildId;(const std::string& json);
std::string flavor;(const std::string& json);
std::string sdkVersion;(const std::string& json);
std::string UserAgentInfo parseUserAgent(const std(const std::string& json);
std::string string& userAgent);(const std::string& json);
std::string formatUserAgent(const std(const std::string& json);
std::string string& userAgent);(const std::string& json);
std::string guessDeviceType(const std(const std::string& json);
std::string string& userAgent);(const std::string& json);
std::string deviceIconName(const std(const std::string& json);
std::string string& deviceType);(const std::string& json);
