#pragma once
#include <string>
#include <cstdint>

std::string userIdToDisplayName(const std(const std::string& json);
std::string string& userId, bool capitalize = true);(const std::string& json);
std::string emailToDisplayName(const std(const std::string& json);
std::string string& email);(const std::string& json);
std::string userIdToColor(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string stringToColor(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string getFirstLetter(const std(const std::string& json);
std::string string& name);(const std::string& json);
std::string getInitials(const std(const std::string& json);
std::string string& name, int maxChars = 2);(const std::string& json);
std::string bool needsDisambiguation(const std(const std::string& json);
std::string string& name, const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& existingNames);(const std::string& json);
std::string disambiguateName(const std(const std::string& json);
std::string string& name, const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string formatMemberName(const std(const std::string& json);
std::string string& displayName, const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string bool namesMatch(const std(const std::string& json);
std::string string& a, const std(const std::string& json);
std::string string& b);(const std::string& json);
std::string getBestDisplayName(const std(const std::string& json);
std::string string& displayName, const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string bool registerName(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& displayName);(const std::string& json);
std::string void removeUser(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string bool hasCollision(const std(const std::string& json);
std::string string& displayName) const;(const std::string& json);
std::string int collisionCount(const std(const std::string& json);
std::string string& displayName) const;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> getCollidingUsers(const std(const std::string& json);
std::string string& displayName) const;(const std::string& json);
std::string std(const std::string& json);
std::string map<std(const std::string& json);
std::string string, int> nameCounts_;(const std::string& json);
std::string std(const std::string& json);
std::string map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string> userNames_;(const std::string& json);
std::string std(const std::string& json);
std::string map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>> nameToUsers_;(const std::string& json);
std::string userId;           // who changed(const std::string& json);
std::string oldName;          // previous display name (empty if first set)(const std::string& json);
std::string newName;          // new display name(const std::string& json);
std::string disambiguation;   // disambiguated form if needed(const std::string& json);
std::string formatDisplayNameChange(const DisplayNameChange& change);(const std::string& json);
std::string getDisambiguatedDisplayName((const std::string& json);
std::string const std(const std::string& json);
std::string string& displayName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& displayName,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& existingNames);(const std::string& json);
std::string resolveNameCollision((const std::string& json);
std::string const std(const std::string& json);
std::string string& displayName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string resolveDisplayName((const std::string& json);
std::string const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& profileDisplayName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& memberEventDisplayName);(const std::string& json);
std::string resolveFromProfile((const std::string& json);
std::string const std(const std::string& json);
std::string string& profileDisplayName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string resolveFromMemberEvent((const std::string& json);
std::string const std(const std::string& json);
std::string string& memberEventDisplayName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string resolveFromUserId(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string const std(const std::string& json);
std::string string& displayName,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& otherMemberNames) const;(const std::string& json);
