#pragma once
#include <string>
#include <cstdint>

std::string inline bool isCallEvent(const std(const std::string& json);
std::string string& type) {(const std::string& json);
std::string senderKey;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string> keysClaimed;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string> payload; // parsed JSON(const std::string& json);
std::string type;        // "m.reaction"(const std::string& json);
std::string key;         // "👍"(const std::string& json);
std::string redactedEventId;         // "redacted_because" event_id(const std::string& json);
std::string redactedSenderId;        // sender of the redaction event(const std::string& json);
std::string transactionId;           // "transaction_id" key(const std::string& json);
std::string prevContentJson;         // "prev_content" key — raw JSON(const std::string& json);
std::string replacesState;           // "replaces_state" key(const std::string& json);
std::string type;                    // "type" key — e.g. "m.room.message"(const std::string& json);
std::string eventId;                 // "event_id" key(const std::string& json);
std::string contentJson;             // "content" key — raw JSON(const std::string& json);
std::string prevContentJson;         // "prev_content" key — raw JSON(const std::string& json);
std::string senderId;                // "sender" key(const std::string& json);
std::string stateKey;                // "state_key" key — null for non-state events(const std::string& json);
std::string roomId;                  // "room_id" key(const std::string& json);
std::string redacts;                 // "redacts" key — event ID being redacted(const std::string& json);
std::string cryptoError;             // mCryptoError(const std::string& json);
std::string cryptoErrorReason;       // mCryptoErrorReason(const std::string& json);
std::string getClearType() const {(const std::string& json);
std::string getSenderKey() const { return decryptionResult.senderKey; }(const std::string& json);
std::string algorithm;       // "algorithm" key — "m.megolm.v1.aes-sha2"(const std::string& json);
std::string ciphertext;      // "ciphertext" key(const std::string& json);
std::string deviceId;        // "device_id" key(const std::string& json);
std::string senderKey;       // "sender_key" key(const std::string& json);
std::string sessionId;       // "session_id" key(const std::string& json);
std::string algorithm;              // "algorithm" key — must be "m.megolm.v1.aes-sha2"(const std::string& json);
std::string ciphertextJson;  // "ciphertext" key — raw JSON object(const std::string& json);
std::string senderKey;       // "sender_key" key(const std::string& json);
std::string roomId;(const std::string& json);
std::string sender;(const std::string& json);
std::string recipient;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string> recipientKeys;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string> keys;(const std::string& json);
std::string algorithm;       // "algorithm" key(const std::string& json);
std::string roomId;          // "room_id" key(const std::string& json);
std::string sessionId;       // "session_id" key(const std::string& json);
std::string sessionKey;      // "session_key" key(const std::string& json);
std::string WithHeldCode withHeldCodeFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string roomId;(const std::string& json);
std::string algorithm;(const std::string& json);
std::string sessionId;(const std::string& json);
std::string senderKey;(const std::string& json);
std::string reason;(const std::string& json);
std::string fromDevice;(const std::string& json);
std::string requestId;       // "request_id" key(const std::string& json);
std::string secretValue;     // "secret" key(const std::string& json);
std::string inline bool isTextMessage(const std(const std::string& json);
std::string string& msgtype) {(const std::string& json);
std::string inline bool isImageMessage(const std(const std::string& json);
std::string string& msgtype) { return msgtype == "m.image"; }(const std::string& json);
std::string inline bool isVideoMessage(const std(const std::string& json);
std::string string& msgtype) { return msgtype == "m.video"; }(const std::string& json);
std::string inline bool isAudioMessage(const std(const std::string& json);
std::string string& msgtype) { return msgtype == "m.audio"; }(const std::string& json);
std::string inline bool isFileMessage(const std(const std::string& json);
std::string string& msgtype) { return msgtype == "m.file"; }(const std::string& json);
std::string inline bool isLocationMessage(const std(const std::string& json);
std::string string& msgtype) { return msgtype == "m.location"; }(const std::string& json);
std::string inline bool isAttachmentMessage(const std(const std::string& json);
std::string string& msgtype) {(const std::string& json);
std::string inline bool isSticker(const std(const std::string& json);
std::string string& type) { return type == "m.sticker"; }(const std::string& json);
std::string inline bool isPollStart(const std(const std::string& json);
std::string string& type) { return type == "m.poll.start"; }(const std::string& json);
std::string inline bool isPollEnd(const std(const std::string& json);
std::string string& type) { return type == "m.poll.end"; }(const std::string& json);
std::string inline bool isPoll(const std(const std::string& json);
std::string string& type) { return isPollStart(type) || isPollEnd(type); }(const std::string& json);
std::string eventId;                 // "event_id" key — latest edit(const std::string& json);
std::string senderId;                // "sender" key(const std::string& json);
std::string inline bool isLocalEchoId(const std(const std::string& json);
std::string string& eventId) {(const std::string& json);
std::string stable;(const std::string& json);
std::string unstable;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> values() const {(const std::string& json);
std::string bool matches(const std(const std::string& json);
std::string string& type) const {(const std::string& json);
std::string type;(const std::string& json);
std::string eventId;(const std::string& json);
std::string clearContentJson;            // decrypted content JSON(const std::string& json);
std::string prevContentJson;(const std::string& json);
std::string cryptoSenderKey;             // curve25519 sender key(const std::string& json);
std::string roomId;(const std::string& json);
std::string redacts;(const std::string& json);
std::string algorithm;                   // e.g. "m.megolm.v1.aes-sha2"(const std::string& json);
std::string static ValidDecryptedEvent fromEncryptedEvent(const Event& ev, const std(const std::string& json);
std::string string& decryptedContentJson);(const std::string& json);
std::string key;                         // "👍"(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> sourceEvents;   // event IDs(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> localEchoEvents;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> sourceEvents;   // event IDs used to build summary(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> localEchos;(const std::string& json);
std::string userId;(const std::string& json);
std::string option;                      // answer ID(const std::string& json);
std::string myVote;                      // my answer ID or null(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> sourceEvents;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> localEchos;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> encryptedRelatedEventIds;(const std::string& json);
std::string contentJson;                 // raw JSON content(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> sourceEvents;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> localEchos;(const std::string& json);
std::string userId;(const std::string& json);
std::string displayName;(const std::string& json);
std::string avatarUrl;(const std::string& json);
std::string getDisambiguatedDisplayName() const {(const std::string& json);
std::string userId;(const std::string& json);
std::string displayName;(const std::string& json);
std::string avatarUrl;(const std::string& json);
std::string inline bool isRoomLocalEchoId(const std(const std::string& json);
std::string string& roomId) {(const std::string& json);
std::string Event parseEvent(const std(const std::string& json);
std::string string& eventJson);(const std::string& json);
std::string UnsignedData parseUnsignedData(const std::string& json);
std::string EncryptedEventContent parseEncryptedEventContent(const std::string& json);
std::string EncryptionEventContent parseEncryptionEventContent(const std::string& json);
std::string RoomKeyContent parseRoomKeyContent(const std::string& json);
std::string RoomKeyWithHeldContent parseRoomKeyWithHeldContent(const std::string& json);
std::string SecretSendEventContent parseSecretSendEventContent(const std::string& json);
std::string userId;(const std::string& json);
std::string displayName;(const std::string& json);
std::string avatarUrl;(const std::string& json);
std::string nextBatch;                   // pagination token, null if no more(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> highlights;     // stemmed words to highlight(const std::string& json);
std::string name;(const std::string& json);
std::string uri;                         // queryUri(const std::string& json);
std::string mimeType;(const std::string& json);
std::string EventSearchResult parseEventSearchResult(const std::string& json);
std::string ContentAttachmentData parseContentAttachmentData(const std::string& json);
std::string inline type(const std(const std::string& json);
std::string string& t) {(const std::string& json);
