#pragma once
#include <string>
#include <cstdint>

std::string formatEventSummary((const std::string& json);
std::string const std(const std::string& json);
std::string string& eventType,      // "m.room.message", "m.room.member", etc.(const std::string& json);
std::string const std(const std::string& json);
std::string string& msgType,        // "m.text", "m.image", etc. (empty for non-message)(const std::string& json);
std::string const std(const std::string& json);
std::string string& senderName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body,           // Message body (may be empty)(const std::string& json);
std::string const std(const std::string& json);
std::string string& membership = "", // "join", "invite", "leave", "ban" (for member events)(const std::string& json);
std::string const std(const std::string& json);
std::string string& displayName = "",// New display name (for member events with displayname changes)(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& eventIds,     // Ordered event IDs(const std::string& json);
std::string const std(const std::string& json);
std::string string& readEventId,               // User's read receipt event ID (empty = none)(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& highlightIds  // Events that should be highlighted(const std::string& json);
std::string formatTypingIndicator((const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& typingUserNames,(const std::string& json);
std::string const std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int>& eventTypeLevels = {}(const std::string& json);
std::string formatMemberNotice((const std::string& json);
std::string const std(const std::string& json);
std::string string& membership,         // new membership(const std::string& json);
std::string "join", "invite", "leave", "ban", "knock"(const std::string& json);
std::string const std(const std::string& json);
std::string string& prevMembership,     // previous membership (empty when first join)(const std::string& json);
std::string const std(const std::string& json);
std::string string& senderId,           // who performed the action(const std::string& json);
std::string const std(const std::string& json);
std::string string& senderName,         // display name of sender(const std::string& json);
std::string const std(const std::string& json);
std::string string& targetUserId,       // who this happened to (state_key)(const std::string& json);
std::string const std(const std::string& json);
std::string string& targetDisplayName,  // display name of target(const std::string& json);
std::string const std(const std::string& json);
std::string string& reason,             // optional reason for kick/ban/invite(const std::string& json);
std::string formatCallNotice((const std::string& json);
std::string const std(const std::string& json);
std::string string& eventType,          // "m.call.invite", "m.call.answer", "m.call.hangup", "m.call.reject"(const std::string& json);
std::string const std(const std::string& json);
std::string string& senderName,(const std::string& json);
std::string formatRedactionNotice(const std(const std::string& json);
std::string string& reason, bool redactedBySameUser, bool isStateEvent);(const std::string& json);
std::string annotateEdited(const std(const std::string& json);
std::string string& body, bool isEdited);(const std::string& json);
std::string formatRoomNameNotice(const std(const std::string& json);
std::string string& senderName, const std(const std::string& json);
std::string string& newName, bool sentByCurrentUser);(const std::string& json);
std::string formatRoomTopicNotice(const std(const std::string& json);
std::string string& senderName, const std(const std::string& json);
std::string string& newTopic, bool sentByCurrentUser);(const std::string& json);
std::string formatRoomAvatarNotice(const std(const std::string& json);
std::string string& senderName, bool isRemoved, bool sentByCurrentUser);(const std::string& json);
std::string formatRoomCreateNotice(const std(const std::string& json);
std::string string& senderName, const std(const std::string& json);
std::string string& predecessorRoomId, bool isDirect, bool sentByCurrentUser);(const std::string& json);
std::string formatRoomTombstoneNotice(const std(const std::string& json);
std::string string& senderName, const std(const std::string& json);
std::string string& replacementRoom, bool sentByCurrentUser);(const std::string& json);
std::string formatRoomEncryptionNotice(const std(const std::string& json);
std::string string& senderName, bool isEnabled, bool sentByCurrentUser);(const std::string& json);
std::string formatPowerLevelNotice(const std(const std::string& json);
std::string string& senderName, bool sentByCurrentUser);(const std::string& json);
std::string formatPowerLevelDiff(const std(const std::string& json);
std::string string& senderName,(const std::string& json);
std::string const std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int>& oldLevels,(const std::string& json);
std::string const std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int>& newLevels,(const std::string& json);
std::string const std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string>& userNames, // userId → displayName(const std::string& json);
std::string formatJoinRulesNotice(const std(const std::string& json);
std::string string& senderName, const std(const std::string& json);
std::string string& newRule, bool sentByCurrentUser);(const std::string& json);
std::string formatHistoryVisibilityNotice(const std(const std::string& json);
std::string string& senderName, const std(const std::string& json);
std::string string& newVisibility, bool sentByCurrentUser);(const std::string& json);
std::string formatGuestAccessNotice(const std(const std::string& json);
std::string string& senderName, bool guestsAllowed, bool sentByCurrentUser);(const std::string& json);
