#pragma once
#include <string>
#include <cstdint>

std::string EventRelationType relationTypeFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string eventId;(const std::string& json);
std::string typeString;          // Raw type string(const std::string& json);
std::string eventId;             // Target event ID(const std::string& json);
std::string RelationContent parseRelation(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string ReplyToContent parseReplyTo(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string bool hasRelation(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string bool isEventReply(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string bool isEventEdit(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string bool isEventReaction(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string bool isThreadRoot(const std(const std::string& json);
std::string string& eventContentJson, const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string bool isThreadReply(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string extractThreadRoot(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string extractEditSource(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string extractReplySource(const std(const std::string& json);
std::string string& eventContentJson);(const std::string& json);
std::string buildReplyRelation(const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string buildEditRelation(const std(const std::string& json);
std::string string& eventId, bool isFallingBack = false);(const std::string& json);
std::string buildThreadRelation(const std(const std::string& json);
std::string string& eventId, bool isFallingBack = false,(const std::string& json);
std::string const std(const std::string& json);
std::string string& replyToEventId = "");(const std::string& json);
std::string buildAnnotationRelation(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string string& key = "");(const std::string& json);
std::string buildReferenceRelation(const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string buildReplyRelationWithThread(const std(const std::string& json);
std::string string& replyToEventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& threadRootEventId);(const std::string& json);
std::string bool validateEdit(const std(const std::string& json);
std::string string& originalEventJson, const std(const std::string& json);
std::string string& replaceEventJson,(const std::string& json);
std::string std(const std::string& json);
std::string string& error);(const std::string& json);
std::string buildNewContent(const std(const std::string& json);
std::string string& body, const std(const std::string& json);
std::string string& msgType,(const std::string& json);
std::string const std(const std::string& json);
std::string string& formattedBody = "",(const std::string& json);
std::string const std(const std::string& json);
std::string string& format = "");(const std::string& json);
std::string relationToJson(const RelationContent& rel) const;(const std::string& json);
std::string static extractStr(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string static int64_t extractInt(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string static bool extractBool(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
