#pragma once
#include <string>
#include <cstdint>

std::string relType;           // "m.thread", "m.reference", "m.replace", "m.annotation"(const std::string& json);
std::string eventId;           // the event this relation points to(const std::string& json);
std::string key;               // for m.annotation(const std::string& json);
std::string the emoji key(const std::string& json);
std::string fallback;          // for m.replace(const std::string& json);
std::string new body text(const std::string& json);
std::string EventRelationInfo parseEventRelation(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool isThreadRoot(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool isReply(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool isEdit(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool isReaction(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string extractThreadRoot(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string extractReplySource(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string extractEditSource(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string buildReplyRelationWithThread(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string string& threadRoot = "");(const std::string& json);
std::string buildThreadRelation(const std(const std::string& json);
std::string string& threadRoot);(const std::string& json);
std::string buildEditRelation(const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string formatRelationDescription(const EventRelationInfo& relation);(const std::string& json);
std::string rootEventId;(const std::string& json);
std::string rootMessageBody;       // first message in thread(const std::string& json);
std::string rootSender;(const std::string& json);
std::string lastReplyBody;(const std::string& json);
std::string lastReplySender;(const std::string& json);
std::string const std(const std::string& json);
std::string string& rootEventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& rootBody,(const std::string& json);
std::string const std(const std::string& json);
std::string string& rootSender,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& replyBodies,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& replySenders,(const std::string& json);
std::string threadSummaryToJson(const ThreadSummary& summary);(const std::string& json);
std::string buildThreadListJson(const std(const std::string& json);
std::string string& eventsJson);(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& eventIds,(const std::string& json);
std::string const std(const std::string& json);
std::string string& readReceiptEventId,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& highlightIds);(const std::string& json);
