#pragma once
#include <string>
#include <cstdint>

std::string bool isStateEvent(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string inline bool isMessageEvent(const std(const std::string& json);
std::string string& t) { return t == EventTypeStr(const std::string& json);
std::string MESSAGE; }(const std::string& json);
std::string inline bool isEncryptedEvent(const std(const std::string& json);
std::string string& t) { return t == EventTypeStr(const std::string& json);
std::string ENCRYPTED; }(const std::string& json);
std::string inline bool isReactionEvent(const std(const std::string& json);
std::string string& t) { return t == EventTypeStr(const std::string& json);
std::string REACTION; }(const std::string& json);
std::string inline bool isStickerEvent(const std(const std::string& json);
std::string string& t) { return t == EventTypeStr(const std::string& json);
std::string STICKER; }(const std::string& json);
std::string inline bool isRedactionEvent(const std(const std::string& json);
std::string string& t) { return t == EventTypeStr(const std::string& json);
std::string REDACTION; }(const std::string& json);
std::string bool isCallEvent(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string bool isVerificationEvent(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string bool isPollEvent(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string inline bool isMembershipEvent(const std(const std::string& json);
std::string string& t) { return t == EventTypeStr(const std::string& json);
std::string STATE_ROOM_MEMBER; }(const std::string& json);
std::string inline bool isTombstoneEvent(const std(const std::string& json);
std::string string& t) { return t == EventTypeStr(const std::string& json);
std::string STATE_ROOM_TOMBSTONE; }(const std::string& json);
std::string bool isMediaMessageType(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string bool isTextMessageType(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> getAllEventTypes();(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> getAllMessageTypes();(const std::string& json);
std::string getEventTypeLabel(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string getMessageTypeLabel(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string routeEventForProcessing(const std(const std::string& json);
std::string string& eventType, const std(const std::string& json);
std::string string& msgType = "");(const std::string& json);
std::string bool isTextMessage(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string bool isImageMessage(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string bool isVideoMessage(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string bool isAudioMessage(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string bool isFileMessage(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string bool isLocationMessage(const std(const std::string& json);
std::string string& msgType);(const std::string& json);
std::string bool isAttachmentMessage(const std(const std::string& json);
std::string string& msgType);     // image|audio|video|file(const std::string& json);
std::string bool isPollEvent(const std(const std::string& json);
std::string string& eventType);            // already declared(const std::string& json);
std::string bool isStickerEvent(const std(const std::string& json);
std::string string& t);                 // already declared(const std::string& json);
std::string bool supportsNotification(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string bool isContentReportable(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string bool isInvitationEvent(const std(const std::string& json);
std::string string& eventType, const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool isReplyRelation(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool shouldRenderInThread(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
