#pragma once
#include <string>
#include <cstdint>

std::string eventId;(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string warningMessage;  // non-fatal issues(const std::string& json);
std::string eventType;(const std::string& json);
std::string msgType;(const std::string& json);
std::string body;(const std::string& json);
std::string formattedBody;(const std::string& json);
std::string url;          // for m.room.avatar etc.(const std::string& json);
std::string filename;     // for file uploads(const std::string& json);
std::string const std(const std::string& json);
std::string string& eventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& eventType,(const std::string& json);
std::string const std(const std::string& json);
std::string string& senderId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& contentJson,(const std::string& json);
std::string const std(const std::string& json);
std::string string& originServerTs,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& blockedUsers(const std::string& json);
std::string EventContent parseEventContent(const std(const std::string& json);
std::string string& eventType, const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool isBodyWithinLimits(const std(const std::string& json);
std::string string& body, int maxLength = 65536);(const std::string& json);
std::string bool isValidEventId(const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string bool isValidSenderId(const std(const std::string& json);
std::string string& senderId);(const std::string& json);
std::string bool isReasonableTimestamp(const std(const std::string& json);
std::string string& originServerTs, int64_t maxFutureMs = 300000);(const std::string& json);
std::string eventValidationToJson(const EventValidation& validation);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> warnings;(const std::string& json);
std::string const std(const std::string& json);
std::string string& eventJson,(const std::string& json);
std::string EventValidationResult validateEventBasic(const std(const std::string& json);
std::string string& eventJson);(const std::string& json);
std::string EventValidationResult validateEventFull(const std(const std::string& json);
std::string string& eventJson);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> getValidationErrors(const EventValidationResult& result);(const std::string& json);
std::string bool isWellFormedEventId(const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string bool isWellFormedRoomId(const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string bool isWellFormedUserId(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string bool isWellFormedEventType(const std(const std::string& json);
std::string string& eventType);(const std::string& json);
std::string EventIntegrityCheck checkEventIntegrity(const std(const std::string& json);
std::string string& eventJson);(const std::string& json);
std::string EventValidationResult validateRedactionEvent(const std(const std::string& json);
std::string string& eventJson);(const std::string& json);
std::string EventValidationResult validateStateEvent(const std(const std::string& json);
std::string string& eventJson);(const std::string& json);
std::string EventValidationResult validateEncryptedEvent(const std(const std::string& json);
std::string string& eventJson);(const std::string& json);
