#pragma once
#include <string>
#include <cstdint>

std::string name;(const std::string& json);
std::string return std(const std::string& json);
std::string hash<std(const std::string& json);
std::string string>{}(n.name);(const std::string& json);
std::string return std(const std::string& json);
std::string hash<std(const std::string& json);
std::string string>{}(e.source.name)(const std::string& json);
std::string ^ (std(const std::string& json);
std::string hash<std(const std::string& json);
std::string string>{}(e.destination.name) << 1);(const std::string& json);
std::string GraphNode getOrCreateNode(const std(const std::string& json);
std::string string& name);(const std::string& json);
std::string void addEdge(const std(const std::string& json);
std::string string& sourceName, const std(const std::string& json);
std::string string& destinationName);(const std::string& json);
std::string toString() const;(const std::string& json);
std::string inline bool hasSpecialGlobChar(const std(const std::string& json);
std::string string& pattern) {(const std::string& json);
std::string return pattern.find('*') != std(const std::string& json);
std::string string(const std::string& json);
std::string npos(const std::string& json);
std::string || pattern.find('?') != std(const std::string& json);
std::string string(const std::string& json);
std::string npos;(const std::string& json);
std::string inline simpleGlobToRegExp(const std(const std::string& json);
std::string string& pattern) {(const std::string& json);
std::string result;(const std::string& json);
std::string inline base64UrlToBase64(const std(const std::string& json);
std::string string& base64Url) {(const std::string& json);
std::string result = base64Url;(const std::string& json);
std::string inline base64ToBase64Url(const std(const std::string& json);
std::string string& base64) {(const std::string& json);
std::string result;(const std::string& json);
std::string inline base64ToUnpaddedBase64(const std(const std::string& json);
std::string string& base64) {(const std::string& json);
std::string result;(const std::string& json);
std::string inline bool isEmail(const std(const std::string& json);
std::string string& s) {(const std::string& json);
std::string if (at == std(const std::string& json);
std::string string(const std::string& json);
std::string npos || at == 0 || at == s.size() - 1) return false;(const std::string& json);
std::string if (s.find('@', at + 1) != std(const std::string& json);
std::string string(const std::string& json);
std::string npos) return false; // only one @(const std::string& json);
std::string return s.find('.', at) != std(const std::string& json);
std::string string(const std::string& json);
std::string npos; // domain must have dot(const std::string& json);
std::string inline ensurePrefix(const std(const std::string& json);
std::string string& s, const std(const std::string& json);
std::string string& prefix) {(const std::string& json);
std::string inline ensureTrailingSlash(const std(const std::string& json);
std::string string& url) {(const std::string& json);
std::string inline ensureProtocol(const std(const std::string& json);
std::string string& url, const std(const std::string& json);
std::string string& protocol = "https") {(const std::string& json);
std::string if (url.find("(const std::string& json);
std::string //") != std(const std::string& json);
std::string string(const std::string& json);
std::string npos) return url;(const std::string& json);
std::string inline getDecimalCodeRepresentation(const uint8_t* bytes5) {(const std::string& json);
std::string localId;(const std::string& json);
std::string roomId;(const std::string& json);
std::string void markForCancel(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string string& roomId) {(const std::string& json);
std::string bool isCancelRequested(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string string& roomId) {(const std::string& json);
std::string void markCancelled(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string string& roomId) {(const std::string& json);
std::string inline removeInvalidRoomNameChars(const std(const std::string& json);
std::string string& name) {(const std::string& json);
std::string result;(const std::string& json);
std::string inline replaceSpaceChars(const std(const std::string& json);
std::string string& input, const std(const std::string& json);
std::string string& replacement = "") {(const std::string& json);
std::string result;(const std::string& json);
std::string inline extractUsefulTextFromReply(const std(const std::string& json);
std::string string& repliedBody) {(const std::string& json);
std::string if (nl == std(const std::string& json);
std::string string(const std::string& json);
std::string npos) nl = repliedBody.size();(const std::string& json);
std::string line = repliedBody.substr(pos, nl - pos);(const std::string& json);
std::string inline extractUsefulTextFromHtmlReply(const std(const std::string& json);
std::string string& repliedHtml) {(const std::string& json);
std::string if (si == std(const std::string& json);
std::string string(const std::string& json);
std::string npos) return repliedHtml;(const std::string& json);
std::string if (ei == std(const std::string& json);
std::string string(const std::string& json);
std::string npos) return repliedHtml;(const std::string& json);
std::string inline bool isMimeTypeImage(const std(const std::string& json);
std::string string& mime) { return mime.compare(0, 6, "image/") == 0; }(const std::string& json);
std::string inline bool isMimeTypeVideo(const std(const std::string& json);
std::string string& mime) { return mime.compare(0, 6, "video/") == 0; }(const std::string& json);
std::string inline bool isMimeTypeAudio(const std(const std::string& json);
std::string string& mime) { return mime.compare(0, 6, "audio/") == 0; }(const std::string& json);
std::string inline bool isMimeTypeText(const std(const std::string& json);
std::string string& mime) { return mime.compare(0, 5, "text/") == 0; }(const std::string& json);
std::string inline bool isMimeTypeApplication(const std(const std::string& json);
std::string string& mime) { return mime.compare(0, 12, "application/") == 0; }(const std::string& json);
std::string inline normalizeMimeType(const std(const std::string& json);
std::string string& mime) {(const std::string& json);
std::string inline formatFingerprint(const std(const std::string& json);
std::string string& raw) {(const std::string& json);
std::string result;(const std::string& json);
std::string upper = raw;(const std::string& json);
std::string inline unescapeHtml(const std(const std::string& json);
std::string string& html) {(const std::string& json);
std::string result;(const std::string& json);
std::string if (semi == std(const std::string& json);
std::string string(const std::string& json);
std::string npos) { result += '&'; continue; }(const std::string& json);
std::string entity = html.substr(i + 1, semi - i - 1);(const std::string& json);
std::string inline void fatalError(const std(const std::string& json);
std::string string& msg, bool isDebug) {(const std::string& json);
std::string inline HomeServerVersion parseHomeServerVersion(const std(const std::string& json);
std::string string& value) {(const std::string& json);
std::string if (dot1 == std(const std::string& json);
std::string string(const std::string& json);
std::string npos) return v;(const std::string& json);
std::string if (dot2 == std(const std::string& json);
std::string string(const std::string& json);
std::string npos) {(const std::string& json);
std::string inline std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> computeViaParams((const std::string& json);
std::string const std(const std::string& json);
std::string string& userHomeserver,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& joinedMemberIds,(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int> serverCounts;(const std::string& json);
std::string if (colon != std(const std::string& json);
std::string string(const std::string& json);
std::string npos) {(const std::string& json);
std::string server = uid.substr(colon + 1);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string pair<std(const std::string& json);
std::string string, int>> sorted(serverCounts.begin(), serverCounts.end());(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> result;(const std::string& json);
std::string reason;              // Why invalid (empty if valid/unknown)(const std::string& json);
std::string const std(const std::string& json);
std::string string& originalRoomId, const std(const std::string& json);
std::string string& replaceRoomId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& originalSender, const std(const std::string& json);
std::string string& replaceSender,(const std::string& json);
std::string const std(const std::string& json);
std::string string& originalType, const std(const std::string& json);
std::string string& replaceType,(const std::string& json);
std::string email;(const std::string& json);
std::string msisdn;(const std::string& json);
std::string countryCode;(const std::string& json);
std::string matrixId;(const std::string& json);
std::string displayName;(const std::string& json);
std::string fullAvatarUrl;(const std::string& json);
std::string url;(const std::string& json);
std::string name;(const std::string& json);
std::string rootThreadEdition;(const std::string& json);
std::string latestThreadEdition;(const std::string& json);
std::string nextBatch;(const std::string& json);
std::string keyId;(const std::string& json);
std::string keySpecJson; // SsssKeySpec serialized(const std::string& json);
std::string errorDetail;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> supportedVersions;   // ["r0.6.1", "v1.4.0", ...](const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, bool> unstableFeatures; // "org.matrix.msc3440" → true(const std::string& json);
std::string inline bool hasUnstableFeature(const ServerVersions& v, const std(const std::string& json);
std::string string& feature) {(const std::string& json);
std::string inline appendParamToUrl(const std(const std::string& json);
std::string string& url, const std(const std::string& json);
std::string string& param, const std(const std::string& json);
std::string string& value) {(const std::string& json);
std::string result = url;(const std::string& json);
std::string result += (result.find('?') != std(const std::string& json);
std::string string(const std::string& json);
std::string npos) ? "&"(const std::string& json);
std::string "?";(const std::string& json);
std::string inline appendParamsToUrl(const std(const std::string& json);
std::string string& url, const std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string>& params) {(const std::string& json);
std::string result = url;(const std::string& json);
std::string result += (result.find('?') != std(const std::string& json);
std::string string(const std::string& json);
std::string npos) ? "&"(const std::string& json);
std::string "?";(const std::string& json);
std::string inline int maxAliasLocalPartLength(const std(const std::string& json);
std::string string& domain) {(const std::string& json);
std::string geoUri;         // RFC5870(const std::string& json);
std::string "geo(const std::string& json);
std::string 40.05,29.24;u=30"(const std::string& json);
std::string description;    // "Big Ben, London, UK"(const std::string& json);
