#pragma once
#include <string>
#include <cstdint>

std::string method;                      // "GET", "POST", "PUT", "DELETE"(const std::string& json);
std::string url;                         // Full URL including https(const std::string& json);
std::string //(const std::string& json);
std::string body;                        // Request body (JSON for Matrix API)(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string> headers;(const std::string& json);
std::string body;                        // Response body(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string> headers;(const std::string& json);
std::string errorMessage;                // Empty on success(const std::string& json);
std::string scheme;          // "https" or "http"(const std::string& json);
std::string host;            // "matrix.example.org"(const std::string& json);
std::string path;            // "/_matrix/client/r0/sync"(const std::string& json);
std::string ParsedUrl parseUrl(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string inline HttpResponse httpGet(const std(const std::string& json);
std::string string& url,(const std::string& json);
std::string const std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string>& headers = {},(const std::string& json);
std::string inline HttpResponse httpPost(const std(const std::string& json);
std::string string& url, const std(const std::string& json);
std::string string& jsonBody,(const std::string& json);
std::string const std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string>& extraHeaders = {},(const std::string& json);
std::string inline HttpResponse httpPut(const std(const std::string& json);
std::string string& url, const std(const std::string& json);
std::string string& jsonBody,(const std::string& json);
std::string inline buildMatrixUrl(const std(const std::string& json);
std::string string& homeserverBase, const std(const std::string& json);
std::string string& path) {(const std::string& json);
std::string url = homeserverBase;(const std::string& json);
std::string inline void addAuthHeader(HttpRequest& req, const std(const std::string& json);
std::string string& accessToken) {(const std::string& json);
std::string buildFormBody(const std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string>& params);(const std::string& json);
std::string errcode;     // "M_FORBIDDEN", "M_UNKNOWN_TOKEN", etc.(const std::string& json);
std::string error;       // Human-readable error message(const std::string& json);
std::string MatrixErrorResponse parseMatrixError(const std(const std::string& json);
std::string string& responseBody);(const std::string& json);
