#pragma once
#include <string>
#include <cstdint>

std::string ThreePidMedium threePidMediumFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string value;               // "alice@example.org" or "1234567890"(const std::string& json);
std::string toMedium() const;(const std::string& json);
std::string getCountryCode() const;(const std::string& json);
std::string static IS_ThreePid parse(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string static bool isEmail(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string static bool isMsisdn(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string matrixId;            // @user(const std::string& json);
std::string example.org(const std::string& json);
std::string IS_SharedState sharedStateFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string sid;                 // Session ID for pending binding(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string mxid;                // Matrix ID(const std::string& json);
std::string token;(const std::string& json);
std::string signatures;(const std::string& json);
std::string defaultServerUrl;    // From login/well-known(const std::string& json);
std::string currentServerUrl;    // Currently configured(const std::string& json);
std::string void setDefaultServer(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string void setCurrentServer(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string getCurrentServerUrl() const;(const std::string& json);
std::string getDefaultServerUrl() const;(const std::string& json);
std::string setNewIdentityServer(const std(const std::string& json);
std::string string& url, std(const std::string& json);
std::string string& error);(const std::string& json);
std::string buildStatusCheckUrl(const std(const std::string& json);
std::string string& serverUrl) const;(const std::string& json);
std::string bool parseStatusResponse(const std(const std::string& json);
std::string string& json) const;(const std::string& json);
std::string bool isValidServerUrl(const std(const std::string& json);
std::string string& url) const;(const std::string& json);
std::string buildBindRequest(const IS_ThreePid& threePid) const;(const std::string& json);
std::string buildUnbindRequest(const IS_ThreePid& threePid) const;(const std::string& json);
std::string buildSubmitTokenRequest(const IS_ThreePid& threePid, const std(const std::string& json);
std::string string& sid,(const std::string& json);
std::string const std(const std::string& json);
std::string string& clientSecret, int token) const;(const std::string& json);
std::string IS_ThreePidBindingStatus parseBindResponse(const std(const std::string& json);
std::string string& json, const IS_ThreePid& threePid) const;(const std::string& json);
std::string void registerBinding(const std(const std::string& json);
std::string string& sid, const IS_ThreePid& threePid);(const std::string& json);
std::string IS_ThreePidBindingStatus getBinding(const std(const std::string& json);
std::string string& sid) const;(const std::string& json);
std::string void cancelBinding(const std(const std::string& json);
std::string string& sid);(const std::string& json);
std::string void finalizeBinding(const std(const std::string& json);
std::string string& sid);(const std::string& json);
std::string void removeBinding(const std(const std::string& json);
std::string string& sid);(const std::string& json);
std::string buildLookupRequest(const std(const std::string& json);
std::string vector<IS_ThreePid>& threePids) const;(const std::string& json);
std::string std(const std::string& json);
std::string vector<IS_FoundThreePid> parseLookupResponse(const std(const std::string& json);
std::string string& json) const;(const std::string& json);
std::string buildConsentRequest(bool consent) const;(const std::string& json);
std::string buildSignInvitationRequest(const std(const std::string& json);
std::string string& token, const std(const std::string& json);
std::string string& secret) const;(const std::string& json);
std::string SignInvitationResult parseSignInvitationResponse(const std(const std::string& json);
std::string string& json) const;(const std::string& json);
std::string threePidToJson(const IS_ThreePid& threePid) const;(const std::string& json);
std::string bindingToJson(const IS_ThreePidBindingStatus& status) const;(const std::string& json);
std::string foundPidToJson(const IS_FoundThreePid& found) const;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, IS_ThreePidBindingStatus> bindings_; // sid → binding(const std::string& json);
std::string static extractStr(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string static int64_t extractInt(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string static bool extractBool(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
