#pragma once
#include <string>
#include <cstdint>

std::string algorithm = "m.megolm_backup.v1.curve25519-aes-sha2";(const std::string& json);
std::string authData;                   // Signed JSON with public key(const std::string& json);
std::string recoveryKey;                // Recovery key for decrypt(const std::string& json);
std::string curve25519Key;              // Curve25519 private key (for encrypt)(const std::string& json);
std::string sessionId;(const std::string& json);
std::string roomId;(const std::string& json);
std::string senderKey;(const std::string& json);
std::string sessionKey;              // Base64-encoded session key(const std::string& json);
std::string roomId;(const std::string& json);
std::string senderKey;(const std::string& json);
std::string sessionId;(const std::string& json);
std::string senderClaimedKeys;       // Ed25519 key(const std::string& json);
std::string roomId;(const std::string& json);
std::string sessionId;               // Base64 of firstMessageIndex + sessionKey(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>> sessions;(const std::string& json);
std::string version;                 // "1", "2", etc.(const std::string& json);
std::string algorithm;               // "m.megolm_backup.v1.curve25519-aes-sha2"(const std::string& json);
std::string authData;               // Signed JSON with public key and signatures(const std::string& json);
std::string etag;                   // For conditional requests(const std::string& json);
std::string error;(const std::string& json);
std::string sessionId;(const std::string& json);
std::string senderKey;(const std::string& json);
std::string sessionKeyBase64;        // Base64 Megolm session key(const std::string& json);
std::string error;(const std::string& json);
std::string sessionId;(const std::string& json);
std::string roomId;(const std::string& json);
std::string senderKey;(const std::string& json);
std::string sessionKey;              // The actual Megolm session key(const std::string& json);
std::string error;(const std::string& json);
std::string error;(const std::string& json);
std::string void setRecoveryKey(const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string void setCurve25519Key(const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string void setBackupVersion(const std(const std::string& json);
std::string string& version);(const std::string& json);
std::string extractPrivateKeyFromRecoveryKey(const std(const std::string& json);
std::string string& recoveryKey);(const std::string& json);
std::string generateRecoveryKey(const std(const std::string& json);
std::string string& curve25519Key);(const std::string& json);
std::string bool validatePassphrase(const std(const std::string& json);
std::string string& passphrase);(const std::string& json);
std::string BackupVersion parseBackupVersion(const std::string& json);
std::string buildCreateBackupVersionRequest(const KeyBackupConfig& config);(const std::string& json);
std::string buildUpdateBackupVersionRequest(const std(const std::string& json);
std::string string& version,(const std::string& json);
std::string const std(const std::string& json);
std::string string& authData);(const std::string& json);
std::string buildDeleteBackupRequest(const std(const std::string& json);
std::string string& version);(const std::string& json);
std::string const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& senderKey,(const std::string& json);
std::string const std(const std::string& json);
std::string string& sessionId, const std(const std::string& json);
std::string string& sessionKeyBase64,(const std::string& json);
std::string encryptSessionDataForBackup(const MegolmSessionExport& session,(const std::string& json);
std::string const std(const std::string& json);
std::string string& authData);(const std::string& json);
std::string encryptSessionsForBackup(const std(const std::string& json);
std::string vector<MegolmSessionExport>& sessions,(const std::string& json);
std::string const std(const std::string& json);
std::string string& authData);(const std::string& json);
std::string buildUploadRoomKeyRequest(const std(const std::string& json);
std::string string& roomId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& sessionId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& encryptedData);(const std::string& json);
std::string buildBatchUploadRequest(const std(const std::string& json);
std::string vector<MegolmSessionExport>& sessions);(const std::string& json);
std::string std(const std::string& json);
std::string vector<RoomKeyBackupData> parseBackupKeysResponse(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> parseRoomBackupKeys(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string parseSessionBackupKey(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& sessionId);(const std::string& json);
std::string decryptBackupKey(const std(const std::string& json);
std::string string& backupAuthData,(const std::string& json);
std::string const std(const std::string& json);
std::string string& recoveryKey);(const std::string& json);
std::string DecryptedSessionData decryptSessionData(const std(const std::string& json);
std::string string& encryptedSessionJson,(const std::string& json);
std::string const std(const std::string& json);
std::string string& backupKey,(const std::string& json);
std::string const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string const std(const std::string& json);
std::string string& backupKeysJson,(const std::string& json);
std::string const std(const std::string& json);
std::string string& backupAuthData,(const std::string& json);
std::string const std(const std::string& json);
std::string string& recoveryKey);(const std::string& json);
std::string bool verifyBackupIntegrity(const std(const std::string& json);
std::string string& backupAuthData);(const std::string& json);
std::string bool verifyRecoveryKeyMatchesBackup(const std(const std::string& json);
std::string string& recoveryKey,(const std::string& json);
std::string const std(const std::string& json);
std::string string& backupAuthData);(const std::string& json);
std::string buildMarkBackupAsTrustedRequest();(const std::string& json);
std::string void markError(const std(const std::string& json);
std::string string& error);(const std::string& json);
std::string progressToJson() const;(const std::string& json);
std::string backupVersionToJson(const BackupVersion& ver) const;(const std::string& json);
std::string decryptResultsToJson(const std(const std::string& json);
std::string vector<BackupSessionResult>& results) const;(const std::string& json);
std::string recoveryKey_;(const std::string& json);
std::string curve25519Key_;(const std::string& json);
std::string generateSessionId(const MegolmSessionExport& session) const;(const std::string& json);
std::string extractAuthDataField(const std(const std::string& json);
std::string string& authData, const std(const std::string& json);
std::string string& field) const;(const std::string& json);
std::string bool validateEncryptionPayload(const std(const std::string& json);
std::string string& encryptedJson) const;(const std::string& json);
