#pragma once
#include <string>
#include <cstdint>

std::string langCode;     // "en", "ru", "zh", etc.(const std::string& json);
std::string langName;     // "English", "Russian"(const std::string& json);
std::string LanguageResult detectLanguageByAlphabet(const std(const std::string& json);
std::string string& text);(const std::string& json);
std::string LanguageResult detectLanguage(const std(const std::string& json);
std::string string& text, DetectionMethod method = DetectionMethod(const std::string& json);
std::string Alphabet);(const std::string& json);
std::string getLanguageLabel(const std(const std::string& json);
std::string string& langCode);(const std::string& json);
std::string bool isScript(const std(const std::string& json);
std::string string& text, const std(const std::string& json);
std::string string& scriptName);(const std::string& json);
std::string langCode;       // "ru"(const std::string& json);
std::string langLabel;      // "RU"(const std::string& json);
std::string userId;         // if specificUserOnly(const std::string& json);
std::string roomId;         // which room(const std::string& json);
std::string void hideLanguage(const std(const std::string& json);
std::string string& langCode, const std(const std::string& json);
std::string string& roomId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userId, bool specificUser, int minutes);(const std::string& json);
std::string bool isHidden(const std(const std::string& json);
std::string string& langCode, const std(const std::string& json);
std::string string& roomId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userId) const;(const std::string& json);
std::string exportJson() const;(const std::string& json);
std::string roomId;(const std::string& json);
std::string void pushDown(const std(const std::string& json);
std::string string& roomId, int minutes);(const std::string& json);
std::string bool isPushedDown(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string void restore(const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string exportJson() const;(const std::string& json);
std::string void add(const std(const std::string& json);
std::string string& emoji);(const std::string& json);
std::string void remove(const std(const std::string& json);
std::string string& emoji);(const std::string& json);
std::string bool isBlocked(const std(const std::string& json);
std::string string& emoji) const;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> getAll() const;(const std::string& json);
std::string exportJson() const;(const std::string& json);
std::string void importJson(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> blocked_;(const std::string& json);
