#pragma once
#include <string>
#include <cstdint>

std::string label;           // display name (e.g. "Big Ben")(const std::string& json);
std::string crs;             // coordinate reference system (default(const std::string& json);
std::string wgs84)(const std::string& json);
std::string label;           // human-readable label(const std::string& json);
std::string GeoUri parseGeoUri(const std(const std::string& json);
std::string string& uri);(const std::string& json);
std::string formatGeoUri(const GeoCoordinate& coord);(const std::string& json);
std::string description;          // Human-readable label (e.g. "Alice's location")(const std::string& json);
std::string assetType;            // "m.self" = user's own location(const std::string& json);
std::string BeaconInfoContent parseBeaconInfo(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string buildBeaconInfoContent(const BeaconInfoContent& info);(const std::string& json);
std::string geoUri;               // "geo(const std::string& json);
std::string 48.858093,2.294694;u=10"(const std::string& json);
std::string BeaconLocationContent parseBeaconLocation(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string buildBeaconLocationContent(const GeoCoordinate& coord, bool unstable);(const std::string& json);
std::string sessionId;             // Unique session ID(const std::string& json);
std::string roomId;(const std::string& json);
std::string userId;                // The sharer(const std::string& json);
std::string description;           // "Alice's live location"(const std::string& json);
std::string assetType = "m.self";  // "m.self" or custom(const std::string& json);
std::string label;                   // e.g. "3 participants"(const std::string& json);
std::string markerColor = "red";(const std::string& json);
std::string apiKey;                 // For Google Maps(const std::string& json);
std::string style;                  // Map style(const std::string& json);
std::string "light", "dark", "satellite"(const std::string& json);
std::string buildStaticMapUrl(const GeoCoordinate& coord, const MapTileConfig& config);(const std::string& json);
std::string buildBoundingBoxMapUrl(const std(const std::string& json);
std::string vector<GeoCoordinate>& coords, const MapTileConfig& config);(const std::string& json);
std::string name;                   // e.g. "Work", "Home"(const std::string& json);
std::string nearestGeofence(const GeoCoordinate& coord,(const std::string& json);
std::string formatLocationMessage(const GeoCoordinate& coord, const std(const std::string& json);
std::string string& label = "");(const std::string& json);
std::string formatLocationHtml(const GeoCoordinate& coord, const std(const std::string& json);
std::string string& label = "",(const std::string& json);
std::string formatLocationDescription(const GeoCoordinate& coord);(const std::string& json);
std::string sessionId;(const std::string& json);
std::string roomId;(const std::string& json);
std::string LocationAction parseLocationAction(const std(const std::string& json);
std::string string& actionJson);(const std::string& json);
std::string locationActionToJson(const LocationAction& action);(const std::string& json);
std::string startLiveSession(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& description, int timeoutSec,(const std::string& json);
std::string std(const std::string& json);
std::string string& error);(const std::string& json);
std::string stopLiveSession(const std(const std::string& json);
std::string string& sessionId);(const std::string& json);
std::string bool isSessionExpired(const std(const std::string& json);
std::string string& sessionId) const;(const std::string& json);
std::string bool isUpdateDue(const std(const std::string& json);
std::string string& sessionId) const;(const std::string& json);
std::string updateLocation(const std(const std::string& json);
std::string string& sessionId, const GeoCoordinate& coord,(const std::string& json);
std::string std(const std::string& json);
std::string string& error);(const std::string& json);
std::string std(const std::string& json);
std::string vector<LiveLocationSession> getActiveSessions(const std(const std::string& json);
std::string string& userId) const;(const std::string& json);
std::string std(const std::string& json);
std::string vector<LiveLocationSession> getRoomSessions(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string bool getSession(const std(const std::string& json);
std::string string& sessionId, LiveLocationSession& out) const;(const std::string& json);
std::string void addBeaconUpdate(const std(const std::string& json);
std::string string& sessionId, const GeoCoordinate& coord);(const std::string& json);
std::string GeoCoordinate getLatestLocation(const std(const std::string& json);
std::string string& sessionId) const;(const std::string& json);
std::string std(const std::string& json);
std::string vector<GeoCoordinate> getLocationHistory(const std(const std::string& json);
std::string string& sessionId) const;(const std::string& json);
std::string bool areSessionsNearby(const std(const std::string& json);
std::string string& sessionA, const std(const std::string& json);
std::string string& sessionB,(const std::string& json);
std::string findNearestSession(const GeoCoordinate& coord,(const std::string& json);
std::string sessionsToJson() const;(const std::string& json);
std::string historyToJson(const std(const std::string& json);
std::string string& sessionId) const;(const std::string& json);
std::string buildRoomMapUrl(const std(const std::string& json);
std::string string& roomId, const MapTileConfig& config) const;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string vector<GeoCoordinate>> locationHistory_; // sessionId → history(const std::string& json);
std::string LiveLocationSession* findSession(const std(const std::string& json);
std::string string& sessionId);(const std::string& json);
std::string const LiveLocationSession* findSession(const std(const std::string& json);
std::string string& sessionId) const;(const std::string& json);
std::string generateSessionId() const;(const std::string& json);
