#pragma once
#include <string>
#include <cstdint>

std::string apiEndpoint;     // e.g. "https(const std::string& json);
std::string //api.openai.com/v1/chat/completions"(const std::string& json);
std::string apiToken;(const std::string& json);
std::string model;           // "gpt-4o-mini" or "claude-3-haiku-20240307"(const std::string& json);
std::string systemPrompt;    // optional system prompt(const std::string& json);
std::string prompt;(const std::string& json);
std::string text;(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string buildOpenAiRequestBody(const LlmConfig& config, const std(const std::string& json);
std::string string& prompt);(const std::string& json);
std::string buildAnthropicRequestBody(const LlmConfig& config, const std(const std::string& json);
std::string string& prompt);(const std::string& json);
std::string buildLlmRequestBody(const LlmConfig& config, const std(const std::string& json);
std::string string& prompt);(const std::string& json);
std::string buildLlmHeaders(const LlmConfig& config);(const std::string& json);
std::string LlmResponse parseOpenAiResponse(const std(const std::string& json);
std::string string& body, int statusCode);(const std::string& json);
std::string LlmResponse parseAnthropicResponse(const std(const std::string& json);
std::string string& body, int statusCode);(const std::string& json);
std::string LlmResponse parseLlmResponse(const std(const std::string& json);
std::string string& body, int statusCode, LlmProvider provider);(const std::string& json);
std::string formatLlmBroadcastMessage(const std(const std::string& json);
std::string string& prompt, const std(const std::string& json);
std::string string& response);(const std::string& json);
std::string mxid;(const std::string& json);
std::string displayName;(const std::string& json);
std::string formatUserDisplayName(const std(const std::string& json);
std::string string& displayName, const std(const std::string& json);
std::string string& mxid, bool showMxid);(const std::string& json);
std::string void hideMxid(const std(const std::string& json);
std::string string& mxid);(const std::string& json);
std::string void showMxid(const std(const std::string& json);
std::string string& mxid);(const std::string& json);
std::string bool isVisible(const std(const std::string& json);
std::string string& mxid) const;(const std::string& json);
std::string void reset(const std(const std::string& json);
std::string string& mxid);(const std::string& json);
std::string exportJson() const;(const std::string& json);
std::string void importJson(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> hidden_;(const std::string& json);
std::string inline bool hasToolCalls(const std(const std::string& json);
std::string string& /*response*/) { return false; }(const std::string& json);
std::string inline extractTextAnswer(const std(const std::string& json);
std::string string& /*response*/) { return ""; }(const std::string& json);
std::string inline getAgentToolsSchema() { return "[]"; }(const std::string& json);
