#pragma once
#include <string>
#include <cstdint>

std::string type;        // "m.login.recaptcha", "m.login.dummy", etc.(const std::string& json);
std::string publicKey;   // reCAPTCHA public key(const std::string& json);
std::string session;(const std::string& json);
std::string RegistrationFlowResult parseRegistrationFlow(const std::string& json);
std::string type;              // "m.login.password", "m.login.token", "m.login.sso"(const std::string& json);
std::string description;       // human-readable(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> stages; // for multi-stage auth(const std::string& json);
std::string userId;(const std::string& json);
std::string password;(const std::string& json);
std::string token;(const std::string& json);
std::string deviceName;(const std::string& json);
std::string deviceId;(const std::string& json);
std::string homeServer;(const std::string& json);
std::string userId;(const std::string& json);
std::string accessToken;(const std::string& json);
std::string refreshToken;(const std::string& json);
std::string deviceId;(const std::string& json);
std::string homeServer;(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string errorCode;(const std::string& json);
std::string std(const std::string& json);
std::string vector<LoginFlow> parseLoginFlowsList(const std(const std::string& json);
std::string string& apiResponseJson);(const std::string& json);
std::string buildLoginBody(const LoginParams& params);(const std::string& json);
std::string buildUserIdentifier(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string bool isValidLoginCredentials(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& password);(const std::string& json);
std::string LoginResult parseLoginResponse(const std(const std::string& json);
std::string string& responseJson, int httpStatus);(const std::string& json);
std::string buildRefreshBody(const std(const std::string& json);
std::string string& refreshToken);(const std::string& json);
std::string bool isRateLimited(const std(const std::string& json);
std::string string& responseJson, int httpStatus);(const std::string& json);
std::string int getRateLimitRetrySeconds(const std(const std::string& json);
std::string string& responseJson);(const std::string& json);
std::string generateDeviceName(const std(const std::string& json);
std::string string& model, const std(const std::string& json);
std::string string& osVersion);(const std::string& json);
std::string generateDeviceId();(const std::string& json);
std::string parseDeviceName(const std(const std::string& json);
std::string string& userAgent);(const std::string& json);
std::string homeServerBaseUrl;(const std::string& json);
std::string identityServerBaseUrl;(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string baseUrl;         // alias for homeServerBaseUrl(const std::string& json);
std::string oidcIssuer;(const std::string& json);
std::string WellKnownResult parseWellKnown(const std(const std::string& json);
std::string string& responseJson);(const std::string& json);
std::string bool needsWellKnownDiscovery(const std(const std::string& json);
std::string string& homeserverUrl);(const std::string& json);
std::string buildWellKnownUrl(const std(const std::string& json);
std::string string& domain);(const std::string& json);
