#pragma once
#include <string>
#include <cstdint>

std::string bool isUserId(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string bool isRoomId(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string bool isRoomAlias(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string bool isEventId(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string bool isGroupId(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string bool isMatrixToPermalink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string bool isAppPermalink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string type;        // "user", "room", "event"(const std::string& json);
std::string roomId;(const std::string& json);
std::string userId;(const std::string& json);
std::string eventId;(const std::string& json);
std::string PermalinkInfo parseMatrixToPermalink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> userIds;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> roomIds;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> roomAliases;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> eventIds;(const std::string& json);
std::string ExtractedIds extractMatrixIds(const std(const std::string& json);
std::string string& text);(const std::string& json);
std::string bool isMxcUrl(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string bool isPhoneNumber(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string bool isValidEmail(const std(const std::string& json);
std::string string& input);(const std::string& json);
std::string extractServerNameFromId(const std(const std::string& json);
std::string string& matrixId);(const std::string& json);
std::string extractUserNameFromId(const std(const std::string& json);
std::string string& matrixId);(const std::string& json);
std::string bool isValidOrderString(const std(const std::string& json);
std::string string& order);(const std::string& json);
std::string candidateAliasFromRoomName(const std(const std::string& json);
std::string string& roomName, const std(const std::string& json);
std::string string& domain, int maxAliasLength = 100);(const std::string& json);
