#pragma once
#include <string>
#include <cstdint>

std::string void setHomeserverBaseUrl(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string const std(const std::string& json);
std::string string& getHomeserverBaseUrl();(const std::string& json);
std::string void setAccessToken(const std(const std::string& json);
std::string string& token);(const std::string& json);
std::string apiGetVersions();(const std::string& json);
std::string apiGetLoginFlows();(const std::string& json);
std::string Credentials apiLogin(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& password,(const std::string& json);
std::string const std(const std::string& json);
std::string string& deviceId = "");(const std::string& json);
std::string apiRegister(const std(const std::string& json);
std::string string& username, const std(const std::string& json);
std::string string& password,(const std::string& json);
std::string const std(const std::string& json);
std::string string& deviceId = "");(const std::string& json);
std::string bool apiUsernameAvailable(const std(const std::string& json);
std::string string& username);(const std::string& json);
std::string SyncResponse apiSync(const std(const std::string& json);
std::string string& filter = "",(const std::string& json);
std::string const std(const std::string& json);
std::string string& since = "",(const std::string& json);
std::string apiCreateRoom(const std(const std::string& json);
std::string string& name = "",(const std::string& json);
std::string const std(const std::string& json);
std::string string& topic = "",(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& inviteUsers = {});(const std::string& json);
std::string apiGetRoomMessages(const std(const std::string& json);
std::string string& roomId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& from = "",(const std::string& json);
std::string const std(const std::string& json);
std::string string& dir = "b",(const std::string& json);
std::string apiSendEvent(const std(const std::string& json);
std::string string& roomId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& eventType,(const std::string& json);
std::string const std(const std::string& json);
std::string string& txnId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string apiJoinRoom(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& reason = "");(const std::string& json);
std::string apiLeaveRoom(const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string apiGetProfile(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string apiGetDisplayName(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string apiSetDisplayName(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& displayName);(const std::string& json);
std::string apiUploadMedia(const std(const std::string& json);
std::string string& fileName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& contentType,(const std::string& json);
std::string apiWhoAmI();(const std::string& json);
std::string apiGetPushRules();(const std::string& json);
std::string apiGetPushRule(const std(const std::string& json);
std::string string& scope, const std(const std::string& json);
std::string string& kind,(const std::string& json);
std::string const std(const std::string& json);
std::string string& ruleId);(const std::string& json);
std::string apiSetPushRule(const std(const std::string& json);
std::string string& scope, const std(const std::string& json);
std::string string& kind,(const std::string& json);
std::string const std(const std::string& json);
std::string string& ruleId, const std(const std::string& json);
std::string string& body);(const std::string& json);
std::string bool apiDeletePushRule(const std(const std::string& json);
std::string string& scope, const std(const std::string& json);
std::string string& kind,(const std::string& json);
std::string const std(const std::string& json);
std::string string& ruleId);(const std::string& json);
std::string apiCreateFilter(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& filterJson);(const std::string& json);
std::string apiPublicRooms(const std(const std::string& json);
std::string string& server = "",(const std::string& json);
std::string const std(const std::string& json);
std::string string& searchTerm = "",(const std::string& json);
std::string apiSearch(const std(const std::string& json);
std::string string& searchTerm,(const std::string& json);
std::string const std(const std::string& json);
std::string string& roomId = "",(const std::string& json);
std::string apiGetRoomMembers(const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string apiInviteUser(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& reason = "");(const std::string& json);
std::string apiKickUser(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& reason = "");(const std::string& json);
std::string apiBanUser(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& reason = "");(const std::string& json);
std::string apiUnbanUser(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string apiRedactEvent(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& eventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& txnId, const std(const std::string& json);
std::string string& reason = "");(const std::string& json);
