#pragma once
#include <string>
#include <cstdint>

std::string MediaAttachmentType attachmentTypeFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string name;                // File name(const std::string& json);
std::string mimeType;            // "image/jpeg", "video/mp4", etc.(const std::string& json);
std::string getSafeMimeType() const;(const std::string& json);
std::string static normalizeMimeType(const std(const std::string& json);
std::string string& mime);(const std::string& json);
std::string static MediaAttachmentType detectType(const std(const std::string& json);
std::string string& mimeType);(const std::string& json);
std::string uploadUrl;               // Server upload endpoint(const std::string& json);
std::string filename;                // Optional filename override(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string contentUri;          // MXC URI when complete(const std::string& json);
std::string contentUri;          // mxc(const std::string& json);
std::string //server/media_id(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string void setUploadUrl(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string formatSizeLimitWarning(int64_t fileSize, int64_t maxSize) const;(const std::string& json);
std::string ContentUploadResponse parseUploadResponse(const std::string& json);
std::string buildUploadRequest(const std(const std::string& json);
std::string string& filename, const std(const std::string& json);
std::string string& mimeType,(const std::string& json);
std::string buildImageContent(const MediaContentAttachmentData& attachment,(const std::string& json);
std::string const std(const std::string& json);
std::string string& mxcUrl,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body = "") const;(const std::string& json);
std::string buildVideoContent(const MediaContentAttachmentData& attachment,(const std::string& json);
std::string const std(const std::string& json);
std::string string& mxcUrl,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body = "") const;(const std::string& json);
std::string buildAudioContent(const MediaContentAttachmentData& attachment,(const std::string& json);
std::string const std(const std::string& json);
std::string string& mxcUrl,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body = "") const;(const std::string& json);
std::string buildFileContent(const MediaContentAttachmentData& attachment,(const std::string& json);
std::string const std(const std::string& json);
std::string string& mxcUrl,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body = "") const;(const std::string& json);
std::string buildMediaContent(const MediaContentAttachmentData& attachment,(const std::string& json);
std::string const std(const std::string& json);
std::string string& mxcUrl,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body = "") const;(const std::string& json);
std::string attachmentToJson(const MediaContentAttachmentData& attachment) const;(const std::string& json);
std::string progressToJson() const;(const std::string& json);
