#pragma once
#include <string>
#include <cstdint>

std::string buildMxcDownloadUrl(const std(const std::string& json);
std::string string& homeserver, const std(const std::string& json);
std::string string& mxcUri);(const std::string& json);
std::string buildMxcThumbnailUrl((const std::string& json);
std::string const std(const std::string& json);
std::string string& homeserver,(const std::string& json);
std::string const std(const std::string& json);
std::string string& mxcUri,(const std::string& json);
std::string const std(const std::string& json);
std::string string& method = "scale"(const std::string& json);
std::string serverName;(const std::string& json);
std::string mediaId;(const std::string& json);
std::string MxcUri parseMxcUri(const std(const std::string& json);
std::string string& mxcUri);(const std::string& json);
std::string truncatedSuffix = "...";(const std::string& json);
std::string formatTextNotification((const std::string& json);
std::string const std(const std::string& json);
std::string string& senderName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body,(const std::string& json);
std::string formatImageNotification(const std(const std::string& json);
std::string string& senderName);(const std::string& json);
std::string formatFileNotification(const std(const std::string& json);
std::string string& senderName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& fileName = "");(const std::string& json);
std::string formatVideoNotification(const std(const std::string& json);
std::string string& senderName);(const std::string& json);
std::string formatAudioNotification(const std(const std::string& json);
std::string string& senderName, bool isVoice = false);(const std::string& json);
std::string formatInviteNotification(const std(const std::string& json);
std::string string& inviterName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& roomName);(const std::string& json);
std::string formatRoomNotification(int messageCount, const std(const std::string& json);
std::string string& roomName);(const std::string& json);
std::string formatStickerNotification(const std(const std::string& json);
std::string string& senderName);(const std::string& json);
std::string formatLocationNotification(const std(const std::string& json);
std::string string& senderName);(const std::string& json);
std::string formatPollNotification(const std(const std::string& json);
std::string string& senderName, bool isStart = true);(const std::string& json);
std::string title;     // Room name + optional sender summary(const std::string& json);
std::string body;      // Message preview(const std::string& json);
std::string ticker;    // Short version for status bar(const std::string& json);
std::string const std(const std::string& json);
std::string string& msgType,          // "m.text", "m.image", etc.(const std::string& json);
std::string const std(const std::string& json);
std::string string& senderName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body,(const std::string& json);
std::string const std(const std::string& json);
std::string string& roomName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& fileName = "",(const std::string& json);
