#pragma once
#include <string>
#include <cstdint>

std::string OidcLoginType loginTypeFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string id;              // "github", "google", "apple", etc.(const std::string& json);
std::string name;            // "GitHub", "Google", "Apple"(const std::string& json);
std::string brand;           // Brand identifier(const std::string& json);
std::string iconUrl;         // Provider icon URL(const std::string& json);
std::string loginUrl;        // SSO login URL for redirect(const std::string& json);
std::string std(const std::string& json);
std::string vector<OidcSsoProvider> oidcParseSsoProviders(const std(const std::string& json);
std::string string& loginFlowsJson);(const std::string& json);
std::string oidcBuildSsoLoginUrl(const std(const std::string& json);
std::string string& baseUrl, const std(const std::string& json);
std::string string& providerId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& redirectUrl);(const std::string& json);
std::string clientName = "Progressive Chat";(const std::string& json);
std::string redirectUri = "chat.progressive.app(const std::string& json);
std::string /oauth/callback";(const std::string& json);
std::string clientUri = "https(const std::string& json);
std::string //progressive.chat";(const std::string& json);
std::string logoUri;(const std::string& json);
std::string tosUri;(const std::string& json);
std::string policyUri;(const std::string& json);
std::string scope = "openid urn(const std::string& json);
std::string matrix(const std::string& json);
std::string org.matrix.msc2967.client(const std::string& json);
std::string api(const std::string& json);
std::string *";(const std::string& json);
std::string codeVerifier;        // 43-128 chars random(const std::string& json);
std::string codeChallenge;       // SHA-256(verifier), base64url encoded(const std::string& json);
std::string bool oidcVerifyPkce(const std(const std::string& json);
std::string string& verifier, const std(const std::string& json);
std::string string& challenge);(const std::string& json);
std::string issuer;(const std::string& json);
std::string authorizationEndpoint;(const std::string& json);
std::string tokenEndpoint;(const std::string& json);
std::string userinfoEndpoint;(const std::string& json);
std::string registrationEndpoint;    // Dynamic client registration(const std::string& json);
std::string endSessionEndpoint;(const std::string& json);
std::string jwksUri;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> scopesSupported;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> responseTypesSupported;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> grantTypesSupported;(const std::string& json);
std::string rawJson;                  // Original JSON response(const std::string& json);
std::string OidcProviderMetadata parseOidcMetadata(const std::string& json);
std::string clientId;(const std::string& json);
std::string clientSecret;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> redirectUris;(const std::string& json);
std::string tokenEndpointAuthMethod;(const std::string& json);
std::string buildClientRegistrationRequest(const OidcConfig& config);(const std::string& json);
std::string OidcClientRegistration parseClientRegistration(const std::string& json);
std::string authorizationUrl;    // Full URL to open in browser(const std::string& json);
std::string state;               // Opaque state for CSRF(const std::string& json);
std::string nonce;               // For ID token verification(const std::string& json);
std::string generateState();(const std::string& json);
std::string generateNonce();(const std::string& json);
std::string grantType = "authorization_code";(const std::string& json);
std::string code;                // Authorization code from callback(const std::string& json);
std::string redirectUri;(const std::string& json);
std::string clientId;(const std::string& json);
std::string codeVerifier;        // PKCE verifier(const std::string& json);
std::string accessToken;(const std::string& json);
std::string refreshToken;(const std::string& json);
std::string idToken;(const std::string& json);
std::string tokenType = "Bearer";(const std::string& json);
std::string scope;(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string buildTokenExchangeRequest(const OidcTokenRequest& req);(const std::string& json);
std::string OidcTokenResponseFull parseTokenResponse(const std::string& json);
std::string grantType = "refresh_token";(const std::string& json);
std::string refreshToken;(const std::string& json);
std::string clientId;(const std::string& json);
std::string scope;(const std::string& json);
std::string buildTokenRefreshRequest(const OidcRefreshRequest& req);(const std::string& json);
std::string userId;              // From /whoami(const std::string& json);
std::string deviceId;(const std::string& json);
std::string homeServer;(const std::string& json);
std::string error;(const std::string& json);
std::string OidcTokenValidation parseWhoamiResponse(const std::string& json);
std::string username;(const std::string& json);
std::string password;            // Optional (can be auto-generated)(const std::string& json);
std::string initialDeviceDisplayName;(const std::string& json);
std::string buildOidcRegistrationRequest(const OidcRegistrationRequest& req);(const std::string& json);
std::string bool oidcIsSsoCallbackUrl(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string extractAuthCodeFromCallback(const std(const std::string& json);
std::string string& callbackUrl);(const std::string& json);
std::string extractStateFromCallback(const std(const std::string& json);
std::string string& callbackUrl);(const std::string& json);
std::string baseUrl;(const std::string& json);
std::string idServer;(const std::string& json);
std::string oidcIssuer;(const std::string& json);
std::string error;(const std::string& json);
std::string OidcWellKnownResult oidcParseWellKnown(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> identityProviders;  // SSO provider IDs(const std::string& json);
std::string std(const std::string& json);
std::string vector<OidcLoginFlow> oidcParseLoginFlows(const std::string& json);
std::string userId;              // @user(const std::string& json);
std::string example.org(const std::string& json);
std::string password;(const std::string& json);
std::string token;               // For token login(const std::string& json);
std::string deviceId;(const std::string& json);
std::string initialDeviceDisplayName;(const std::string& json);
std::string buildPasswordLoginRequest(const LoginCredentials& creds);(const std::string& json);
std::string buildTokenLoginRequest(const LoginCredentials& creds);(const std::string& json);
