#pragma once
#include <string>
#include <cstdint>

std::string clientName;          // "Progressive Chat"(const std::string& json);
std::string redirectUri;         // "chat.progressive.app(const std::string& json);
std::string /" (custom scheme)(const std::string& json);
std::string clientUri;           // "https(const std::string& json);
std::string //progressive.chat"(const std::string& json);
std::string logoUri;             // app logo URL(const std::string& json);
std::string tosUri;              // terms of service(const std::string& json);
std::string policyUri;           // privacy policy(const std::string& json);
std::string issuer;              // OIDC issuer URL (e.g. "https(const std::string& json);
std::string //auth.matrix.org")(const std::string& json);
std::string authorizationEndpoint;(const std::string& json);
std::string tokenEndpoint;(const std::string& json);
std::string registrationEndpoint;  // Dynamic client registration(const std::string& json);
std::string accountManagementUri;  // MSC4191(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string codeVerifier;        // 43-128 chars, [A-Za-z0-9\-._~](const std::string& json);
std::string codeChallenge;       // SHA-256(codeVerifier), base64url(const std::string& json);
std::string authorizationUrl;    // Full OIDC authorization URL to open in browser(const std::string& json);
std::string state;               // Opaque state parameter (for CSRF protection)(const std::string& json);
std::string accessToken;(const std::string& json);
std::string refreshToken;(const std::string& json);
std::string userId;              // From Matrix /whoami after getting token(const std::string& json);
std::string deviceId;(const std::string& json);
std::string homeServer;(const std::string& json);
std::string errorMessage;(const std::string& json);
std::string OidcDiscovery discoverOidc(const std(const std::string& json);
std::string string& homeserverUrl);(const std::string& json);
std::string bool supportsOidcLogin(const std(const std::string& json);
std::string string& homeserverUrl);(const std::string& json);
std::string OidcDiscovery fetchOAuthMetadata(const std(const std::string& json);
std::string string& issuerUrl);(const std::string& json);
std::string buildOAuthAuthorizationUrl((const std::string& json);
std::string const std(const std::string& json);
std::string string& clientId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& redirectUri,(const std::string& json);
std::string const std(const std::string& json);
std::string string& state,(const std::string& json);
std::string const std(const std::string& json);
std::string string& pkceChallenge,(const std::string& json);
std::string const std(const std::string& json);
std::string string& prompt = "login",   // "login" or "create"(const std::string& json);
std::string const std(const std::string& json);
std::string string& loginHint = ""(const std::string& json);
std::string registerOidcClient((const std::string& json);
std::string const std(const std::string& json);
std::string string& registrationEndpoint,(const std::string& json);
std::string const std(const std::string& json);
std::string string& tokenEndpoint,(const std::string& json);
std::string const std(const std::string& json);
std::string string& clientId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& redirectUri,(const std::string& json);
std::string const std(const std::string& json);
std::string string& code,(const std::string& json);
std::string const std(const std::string& json);
std::string string& codeVerifier(const std::string& json);
std::string fullUrl;            // The complete callback URL (for token exchange)(const std::string& json);
std::string code;               // Authorization code (if SUCCESS)(const std::string& json);
std::string state;              // State parameter for verification(const std::string& json);
std::string ParsedOAuthCallback parseOAuthCallback(const std(const std::string& json);
std::string string& url, const std(const std::string& json);
std::string string& redirectUri);(const std::string& json);
std::string generateOAuthState();(const std::string& json);
