#pragma once
#include <string>
#include <cstdint>

std::string data;     // output data (JSON, pickle, etc.)(const std::string& json);
std::string OlmAccountResult unpickle(const std(const std::string& json);
std::string string& key, const std(const std::string& json);
std::string string& pickle);(const std::string& json);
std::string OlmAccountResult pickle(const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string OlmAccountResult sign(const std(const std::string& json);
std::string string& message);(const std::string& json);
std::string data;(const std::string& json);
std::string const std(const std::string& json);
std::string string& theirIdentityKey, const std(const std::string& json);
std::string string& theirOneTimeKey);(const std::string& json);
std::string OlmSessionResult createInbound(OlmAccount& account, const std(const std::string& json);
std::string string& preKeyMessage);(const std::string& json);
std::string const std(const std::string& json);
std::string string& theirIdentityKey, const std(const std::string& json);
std::string string& encryptedMessage);(const std::string& json);
std::string OlmSessionResult encrypt(const std(const std::string& json);
std::string string& plaintext);(const std::string& json);
std::string OlmSessionResult decrypt(const std(const std::string& json);
std::string string& encryptedMessage, int messageType);(const std::string& json);
std::string OlmSessionResult pickle(const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string OlmSessionResult unpickle(const std(const std::string& json);
std::string string& key, const std(const std::string& json);
std::string string& pickle);(const std::string& json);
std::string bool matchesInbound(const std(const std::string& json);
std::string string& preKeyMessage);(const std::string& json);
std::string data;        // encrypted message or decrypted plaintext(const std::string& json);
std::string sessionId;   // unique session identifier(const std::string& json);
std::string sessionKey;  // key for sharing(const std::string& json);
std::string plaintext;(const std::string& json);
std::string MegolmSessionResult encrypt(const std(const std::string& json);
std::string string& plaintext);(const std::string& json);
std::string MegolmSessionResult pickle(const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string MegolmSessionResult unpickle(const std(const std::string& json);
std::string string& key, const std(const std::string& json);
std::string string& pickle);(const std::string& json);
std::string MegolmInboundResult create(const std(const std::string& json);
std::string string& sessionKey);(const std::string& json);
std::string MegolmInboundResult decrypt(const std(const std::string& json);
std::string string& encryptedMessage);(const std::string& json);
std::string MegolmSessionResult importSession(const std(const std::string& json);
std::string string& sessionKey);(const std::string& json);
std::string MegolmSessionResult exportSession(const std(const std::string& json);
std::string string& messageIndex);(const std::string& json);
std::string MegolmSessionResult pickle(const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string MegolmSessionResult unpickle(const std(const std::string& json);
std::string string& key, const std(const std::string& json);
std::string string& pickle);(const std::string& json);
std::string data;         // public key, MAC, or emoji codes(const std::string& json);
std::string SasResult setTheirPublicKey(const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string SasResult generateBytes(const std(const std::string& json);
std::string string& extraInfo, int length = 6);(const std::string& json);
std::string SasResult calculateMac(const std(const std::string& json);
std::string string& input, const std(const std::string& json);
std::string string& info);(const std::string& json);
std::string generateRandomBytes(int count);(const std::string& json);
std::string olmErrorToString(OlmError error);(const std::string& json);
std::string formatPickle(const std(const std::string& json);
std::string string& type, const std(const std::string& json);
std::string string& pickle);(const std::string& json);
