#pragma once
#include <string>
#include <cstdint>

std::string userId;(const std::string& json);
std::string deviceId;(const std::string& json);
std::string identityKeysJson;  // {"ed25519"(const std::string& json);
std::string "...","curve25519"(const std::string& json);
std::string "..."}(const std::string& json);
std::string OlmAccountData createOlmAccount(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& deviceId);(const std::string& json);
std::string OlmAccountData unpickleOlmAccount(const std(const std::string& json);
std::string string& pickled, const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& deviceId);(const std::string& json);
std::string pickleOlmAccount(const OlmAccountData& account);(const std::string& json);
std::string getAccountIdentityKeys(const OlmAccountData& account);(const std::string& json);
std::string generateOneTimeKeys(OlmAccountData& account, int count);(const std::string& json);
std::string generateFallbackKey(OlmAccountData& account);(const std::string& json);
std::string accountSign(const OlmAccountData& account, const std(const std::string& json);
std::string string& message);(const std::string& json);
std::string sessionId;         // Unique session identifier(const std::string& json);
std::string theirIdentityKey;  // Curve25519 key of the other party(const std::string& json);
std::string const std(const std::string& json);
std::string string& theirIdentityKey, const std(const std::string& json);
std::string string& oneTimeKeyMessage);(const std::string& json);
std::string const std(const std::string& json);
std::string string& theirIdentityKey, const std(const std::string& json);
std::string string& theirOneTimeKey);(const std::string& json);
std::string olmEncryptMessage(OlmSessionData& session, const std(const std::string& json);
std::string string& plaintext);(const std::string& json);
std::string olmDecryptMessage(OlmSessionData& session, const std(const std::string& json);
std::string string& ciphertextBase64);(const std::string& json);
std::string bool olmMatchesInboundSession(OlmSessionData& session, const std(const std::string& json);
std::string string& theirIdentityKey,(const std::string& json);
std::string const std(const std::string& json);
std::string string& oneTimeKeyMessage);(const std::string& json);
std::string pickleOlmSession(const OlmSessionData& session);(const std::string& json);
std::string OlmSessionData unpickleOlmSession(const std(const std::string& json);
std::string string& pickled, OlmAccountData& account);(const std::string& json);
std::string bool verifyDeviceSignature(const std(const std::string& json);
std::string string& deviceKeysJson,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& deviceId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& signKeyB64, const std(const std::string& json);
std::string string& signatureB64);(const std::string& json);
std::string computeDeviceFingerprint(const std(const std::string& json);
std::string string& identityKeyBase64);(const std::string& json);
std::string void addSession(const std(const std::string& json);
std::string string& senderKey, const std(const std::string& json);
std::string string& sessionId,(const std::string& json);
std::string OlmSessionData* findSession(const std(const std::string& json);
std::string string& senderKey, const std(const std::string& json);
std::string string& sessionId);(const std::string& json);
std::string void removeSession(const std(const std::string& json);
std::string string& senderKey, const std(const std::string& json);
std::string string& sessionId);(const std::string& json);
std::string senderKey;(const std::string& json);
std::string sessionId;(const std::string& json);
std::string return std(const std::string& json);
std::string hash<std(const std::string& json);
std::string string>()(k.senderKey + k.sessionId);(const std::string& json);
std::string signEvent(const OlmAccountData& account, const std(const std::string& json);
std::string string& eventJson);(const std::string& json);
std::string bool verifyEventSignature(const std(const std::string& json);
std::string string& eventJson, const std(const std::string& json);
std::string string& signKeyB64);(const std::string& json);
