#pragma once
#include <string>
#include <cstdint>

std::string fullUrl;          // https(const std::string& json);
std::string //matrix.to/#/!room(const std::string& json);
std::string server/$event(const std::string& json);
std::string roomId;(const std::string& json);
std::string userId;(const std::string& json);
std::string eventId;(const std::string& json);
std::string roomAlias;(const std::string& json);
std::string type;             // "room", "user", "event"(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> viaParameters; // via server names(const std::string& json);
std::string email;            // invitee email(const std::string& json);
std::string signUrl;          // identity server sign URL(const std::string& json);
std::string identityServer;   // identity server host(const std::string& json);
std::string token;            // invitation token(const std::string& json);
std::string privateKey;       // invitation private key(const std::string& json);
std::string roomName;         // room name from params(const std::string& json);
std::string inviterName;      // inviter name from params(const std::string& json);
std::string roomAvatarUrl;    // room avatar from params(const std::string& json);
std::string roomType;         // room type from params(const std::string& json);
std::string buildRoomPermalink(const std(const std::string& json);
std::string string& roomIdOrAlias);(const std::string& json);
std::string buildUserPermalink(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string buildEventPermalink(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string buildMatrixSchemeLink(const std(const std::string& json);
std::string string& type, const std(const std::string& json);
std::string string& id);(const std::string& json);
std::string PermalinkResult parsePermalink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string bool isPermalink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string extractRoomIdFromPermalink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string extractEventIdFromPermalink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string extractUserIdFromPermalink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string formatPermalinkForShare(const PermalinkResult& info);(const std::string& json);
std::string bool isSameRoomPermalink(const std(const std::string& json);
std::string string& url1, const std(const std::string& json);
std::string string& url2);(const std::string& json);
std::string PermalinkResult parsePermalinkFull(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> extractViaParameters(const std(const std::string& json);
std::string string& fragment);(const std::string& json);
std::string bool isEmailInviteLink(const std(const std::string& json);
std::string string& url);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> computeViaParams((const std::string& json);
std::string const std(const std::string& json);
std::string string& myUserId,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& memberUserIds,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& historicalUserIds = {},(const std::string& json);
std::string formatViaParamsUrl(const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& viaServers);(const std::string& json);
