#pragma once
#include <string>
#include <cstdint>

std::string eventId;             // Matrix event ID(const std::string& json);
std::string roomId;(const std::string& json);
std::string senderId;            // Original sender(const std::string& json);
std::string senderName;          // Display name(const std::string& json);
std::string body;                // Message body (truncated for preview)(const std::string& json);
std::string eventType;           // "m.room.message", etc.(const std::string& json);
std::string pinnedBy;            // Who pinned it(const std::string& json);
std::string previewText;         // Formatted preview text(const std::string& json);
std::string roomId;(const std::string& json);
std::string rawStateContent;     // Original state JSON(const std::string& json);
std::string pinEvent(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& eventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& pinnedBy, int userPowerLevel,(const std::string& json);
std::string std(const std::string& json);
std::string string& error);(const std::string& json);
std::string unpinEvent(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& eventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& removedBy, int userPowerLevel,(const std::string& json);
std::string std(const std::string& json);
std::string string& error);(const std::string& json);
std::string togglePin(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& eventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& userId, int userPowerLevel,(const std::string& json);
std::string std(const std::string& json);
std::string string& error);(const std::string& json);
std::string void loadState(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& stateContentJson);(const std::string& json);
std::string void setEventMetadata(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& eventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& senderId, const std(const std::string& json);
std::string string& senderName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& body, const std(const std::string& json);
std::string string& eventType,(const std::string& json);
std::string std(const std::string& json);
std::string vector<PinnedEventInfo> getPinnedEvents(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string bool isEventPinned(const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& eventId) const;(const std::string& json);
std::string int getPinnedCount(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string formatPinnedList(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string formatPinnedPreview(const PinnedEventInfo& event) const;(const std::string& json);
std::string pinnedEventsToJson(const std(const std::string& json);
std::string string& roomId) const;(const std::string& json);
std::string static buildPinnedEventsContent(const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& eventIds);(const std::string& json);
std::string static std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> parsePinnedEventIds(const std(const std::string& json);
std::string string& stateContentJson);(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>> pinned_;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, PinnedEventInfo>> metadata_;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& getPinnedIds(const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string buildPreview(const std(const std::string& json);
std::string string& body, const std(const std::string& json);
std::string string& senderName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& eventType, bool hasImage, bool hasFile, bool hasVideo) const;(const std::string& json);
