#pragma once
#include <string>
#include <cstdint>

std::string eventId;(const std::string& json);
std::string pinnedBy;       // who pinned it(const std::string& json);
std::string body;           // message preview (from cache)(const std::string& json);
std::string senderName;     // original message sender(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> parsePinnedEventIds(const std(const std::string& json);
std::string string& stateContentJson);(const std::string& json);
std::string formatPinnedEventsText(const std(const std::string& json);
std::string vector<PinnedEvent>& events);(const std::string& json);
std::string pinnedEventsToJson(const std(const std::string& json);
std::string vector<PinnedEvent>& events, const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string buildPinnedEventsContent(const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& eventIds);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> parsePinnedEventIds(const std(const std::string& json);
std::string string& stateContentJson);(const std::string& json);
std::string formatPinnedEventsText(const std(const std::string& json);
std::string vector<PinnedEvent>& events);(const std::string& json);
std::string pinnedEventsToJson(const std(const std::string& json);
std::string vector<PinnedEvent>& events, const std(const std::string& json);
std::string string& roomId);(const std::string& json);
std::string buildPinnedEventsContent(const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& eventIds);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> pinned;(const std::string& json);
std::string eventId;(const std::string& json);
std::string changedBy;(const std::string& json);
std::string PinnedEventsContent parsePinnedEventsContent(const std(const std::string& json);
std::string string& stateContentJson);(const std::string& json);
std::string bool isEventPinned(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& pinnedIds);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> pinEvent(const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& currentPins, const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> unpinEvent(const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& currentPins, const std(const std::string& json);
std::string string& eventId);(const std::string& json);
std::string formatPinnedEventsMessage(const std(const std::string& json);
std::string vector<PinnedEvent>& events);(const std::string& json);
