#pragma once
#include <string>
#include <cstdint>

std::string id;            // "option_1", "option_2", etc.(const std::string& json);
std::string text;          // Option text (max 340 chars)(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> voterIds; // Who voted for this option(const std::string& json);
std::string pollId;                // Unique poll ID(const std::string& json);
std::string question;              // Poll question text(const std::string& json);
std::string pollId;(const std::string& json);
std::string voterId;(const std::string& json);
std::string voterName;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> selectedOptionIds; // Which options user selected(const std::string& json);
std::string pollId;(const std::string& json);
std::string reasonText;            // Optional reason for closing(const std::string& json);
std::string myVote;                   // Which option(s) current user voted for(const std::string& json);
std::string question;(const std::string& json);
std::string plainText;               // "Question?\nOption 1(const std::string& json);
std::string 5 votes (50%)\nOption 2(const std::string& json);
std::string 3 votes (30%)..."(const std::string& json);
std::string htmlBody;                // Rich HTML with progress bars(const std::string& json);
std::string closedBy;(const std::string& json);
std::string buildPollStartContent(const std(const std::string& json);
std::string string& question,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& optionTexts,(const std::string& json);
std::string bool unstable, std(const std::string& json);
std::string string& error);(const std::string& json);
std::string PollContent parsePollStartContent(const std(const std::string& json);
std::string string& contentJson, bool unstable);(const std::string& json);
std::string bool isValidPollQuestion(const std(const std::string& json);
std::string string& question);(const std::string& json);
std::string bool isValidPollOption(const std(const std::string& json);
std::string string& text);(const std::string& json);
std::string buildPollResponseContent(const std(const std::string& json);
std::string string& pollId,(const std::string& json);
std::string const std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string>& selectedOptionIds,(const std::string& json);
std::string PollVote parsePollResponseContent(const std(const std::string& json);
std::string string& contentJson, const std(const std::string& json);
std::string string& voterId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& voterName, bool unstable);(const std::string& json);
std::string buildPollEndContent(const std(const std::string& json);
std::string string& pollId, const std(const std::string& json);
std::string string& reason, bool unstable);(const std::string& json);
std::string PollEnd parsePollEndContent(const std(const std::string& json);
std::string string& contentJson, bool unstable);(const std::string& json);
std::string void setMyVote(PollResultFull& result, const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string formatPollPlainText(const PollEventDisplay& display);(const std::string& json);
std::string formatPollHtml(const PollEventDisplay& display);(const std::string& json);
std::string getWinnerText(const PollResultFull& result) const;(const std::string& json);
std::string bool isPollEvent(const std(const std::string& json);
std::string string& eventType) const;(const std::string& json);
std::string getPollEventDescription(const std(const std::string& json);
std::string string& eventType) const;(const std::string& json);
std::string generatePollId() const;(const std::string& json);
std::string optionIdFromIndex(int index) const;(const std::string& json);
std::string inline PollType pollTypeFromString(const std(const std::string& json);
std::string string& s) {(const std::string& json);
