#pragma once
#include <string>
#include <cstdint>

std::string name;                // Function/module name(const std::string& json);
std::string name;(const std::string& json);
std::string format;              // "text" or "json"(const std::string& json);
std::string label;(const std::string& json);
std::string actionName;          // "back_to_menu", "open_room", "send_message"(const std::string& json);
std::string context;             // "room_id(const std::string& json);
std::string !abc(const std::string& json);
std::string org" or extra info(const std::string& json);
std::string actionName;(const std::string& json);
std::string actionPattern;       // "back_to_*", "*_menu", exact name, or regex-like(const std::string& json);
std::string int start(const std(const std::string& json);
std::string string& name);(const std::string& json);
std::string int64_t stop(const std(const std::string& json);
std::string string& name);(const std::string& json);
std::string ScopeTimer(const std(const std::string& json);
std::string string& name);(const std::string& json);
std::string name_;(const std::string& json);
std::string static ScopeTimer scope(const std(const std::string& json);
std::string string& name) { return ScopeTimer(name); }(const std::string& json);
std::string int startAction(const std(const std::string& json);
std::string string& actionName, const std(const std::string& json);
std::string string& context = "",(const std::string& json);
std::string int64_t measureAction(const std(const std::string& json);
std::string string& actionName, int64_t startNs);(const std::string& json);
std::string void setActionBudget(const std(const std::string& json);
std::string string& actionPattern, int64_t budgetNs);(const std::string& json);
std::string bool lastActionWithinBudget(const std(const std::string& json);
std::string string& actionName) const;(const std::string& json);
std::string ActionStats getActionStats(const std(const std::string& json);
std::string string& actionName) const;(const std::string& json);
std::string MemorySnapshot takeMemorySnapshot(const std(const std::string& json);
std::string string& label = "");(const std::string& json);
std::string reportToJson() const;(const std::string& json);
std::string reportToText() const;(const std::string& json);
std::string summaryToJson(const ProfileSummary& s) const;(const std::string& json);
std::string ProfileSummary getSummary(const std(const std::string& json);
std::string string& name) const;(const std::string& json);
std::string actionReportToJson() const;(const std::string& json);
std::string actionReportToText() const;(const std::string& json);
std::string realTimeSnapshotJson() const;(const std::string& json);
std::string realTimeSnapshotText() const;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> recentViolations(int windowSec = 30) const;(const std::string& json);
std::string static colorForDuration(int64_t durationNs, int64_t budgetNs = 200000000LL);(const std::string& json);
std::string static colorForFps(double fps);(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, ProfileSummary> summaries_;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, ActionStats> actionStats_;(const std::string& json);
std::string static formatNs(int64_t ns);(const std::string& json);
std::string static formatBytes(int64_t bytes);(const std::string& json);
