#pragma once
#include <string>
#include <cstdint>

std::string kind;              // "event_match", "contains_display_name", etc.(const std::string& json);
std::string key;               // "content.body", "room_id", etc.(const std::string& json);
std::string pattern;           // match pattern or value(const std::string& json);
std::string description;       // human-readable(const std::string& json);
std::string "Message contains 'hello'"(const std::string& json);
std::string ruleId;(const std::string& json);
std::string kind;              // "override", "underride", "content", "room", "sender"(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> actions; // "notify", "dont_notify", "coalesce"(const std::string& json);
std::string soundName;(const std::string& json);
std::string PushRuleSet parsePushRules(const std(const std::string& json);
std::string string& apiResponseJson);(const std::string& json);
std::string PushCondition parsePushCondition(const std(const std::string& json);
std::string string& conditionJson);(const std::string& json);
std::string describePushCondition(const PushCondition& condition);(const std::string& json);
std::string formatPushRuleConditions(const std(const std::string& json);
std::string vector<PushCondition>& conditions);(const std::string& json);
std::string formatPushRuleItem(const PushRule& rule);(const std::string& json);
std::string bool isKnownPushRuleKind(const std(const std::string& json);
std::string string& kind);(const std::string& json);
std::string getRuleKindDescription(const std(const std::string& json);
std::string string& kind, bool enabled);(const std::string& json);
std::string bool isMsc3061SharedKey(const std(const std::string& json);
std::string string& roomKeyContentJson);(const std::string& json);
std::string formatMsc3061Status(bool isShared, const std(const std::string& json);
std::string string& visibilitySetting);(const std::string& json);
std::string bool canShareHistory(const std(const std::string& json);
std::string string& roomVisibility);(const std::string& json);
std::string sound;           // for SET_TWEAK_SOUND ("default", "ring", or custom URI)(const std::string& json);
std::string kind;            // "kind" — "event_match", "contains_display_name", etc.(const std::string& json);
std::string key;             // "key" — dot-separated field path(const std::string& json);
std::string pattern;         // "pattern" — glob pattern(const std::string& json);
std::string iz;              // "is" — value for room_member_count conditions(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> actionsRaw;     // "actions" — raw JSON list(const std::string& json);
std::string ruleId;                      // "rule_id"(const std::string& json);
std::string pattern;                     // "pattern" — for content rules(const std::string& json);
std::string RestPushRule findDefaultRule(const std(const std::string& json);
std::string string& ruleId, RuleSetKey* outKind = nullptr) const;(const std::string& json);
std::string RuleSet parseRuleSet(const std::string& json);
std::string ruleSetToJson(const RuleSet& rs);(const std::string& json);
std::string matchedRuleId;     // which rule triggered the result(const std::string& json);
std::string matchedAction;     // "notify", "dont_notify", "coalesce"(const std::string& json);
std::string const std(const std::string& json);
std::string string& eventJson,(const std::string& json);
std::string const std(const std::string& json);
std::string string& myDisplayName,(const std::string& json);
std::string const std(const std::string& json);
std::string string& myUserId);(const std::string& json);
std::string const std(const std::string& json);
std::string string& eventType, const std(const std::string& json);
std::string string& sender,(const std::string& json);
std::string const std(const std::string& json);
std::string string& roomId, const std(const std::string& json);
std::string string& body,(const std::string& json);
std::string const std(const std::string& json);
std::string string& myDisplayName, const std(const std::string& json);
std::string string& myUserId);(const std::string& json);
