#pragma once
#include <string>
#include <cstdint>

std::string inline buildReplyRelation(const std(const std::string& json);
std::string string& eventId) {(const std::string& json);
std::string inline buildThreadRelation((const std::string& json);
std::string const std(const std::string& json);
std::string string& rootEventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& latestEventId,(const std::string& json);
std::string inline buildReplaceRelation(const std(const std::string& json);
std::string string& eventId) {(const std::string& json);
std::string inline buildReactionRelation(const std(const std::string& json);
std::string string& eventId, const std(const std::string& json);
std::string string& key) {(const std::string& json);
std::string inline buildReferenceRelation(const std(const std::string& json);
std::string string& eventId) {(const std::string& json);
std::string inline wrapWithRelation(const std(const std::string& json);
std::string string& contentJson, const std(const std::string& json);
std::string string& relationJson) {(const std::string& json);
std::string result = contentJson;(const std::string& json);
std::string inline buildNewContent(const std(const std::string& json);
std::string string& msgType, const std(const std::string& json);
std::string string& body,(const std::string& json);
std::string const std(const std::string& json);
std::string string& formattedBody = "",(const std::string& json);
std::string const std(const std::string& json);
std::string string& format = "org.matrix.custom.html")(const std::string& json);
std::string result = R"({"msgtype"(const std::string& json);
std::string ")" + msgType + R"(","body"(const std::string& json);
std::string ")" + body + R"(")";(const std::string& json);
std::string inline buildEditContent((const std::string& json);
std::string const std(const std::string& json);
std::string string& originalEventId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& msgType,(const std::string& json);
std::string const std(const std::string& json);
std::string string& newBody,(const std::string& json);
std::string const std(const std::string& json);
std::string string& newFormattedBody = "")(const std::string& json);
std::string content = R"({"msgtype"(const std::string& json);
std::string ")" + msgType + R"(","body"(const std::string& json);
std::string " * edited")" + R"(")";(const std::string& json);
std::string relation = buildReplaceRelation(originalEventId);(const std::string& json);
std::string newContent = buildNewContent(msgType, newBody, newFormattedBody);(const std::string& json);
std::string result = content;(const std::string& json);
std::string inline buildReplyFallbackBody((const std::string& json);
std::string const std(const std::string& json);
std::string string& repliedAuthor,(const std::string& json);
std::string const std(const std::string& json);
std::string string& repliedBody,(const std::string& json);
std::string const std(const std::string& json);
std::string string& myReply)(const std::string& json);
std::string result;(const std::string& json);
std::string inline buildReplyFallbackHtml((const std::string& json);
std::string const std(const std::string& json);
std::string string& repliedAuthor,(const std::string& json);
std::string const std(const std::string& json);
std::string string& repliedAuthorId,(const std::string& json);
std::string const std(const std::string& json);
std::string string& repliedHtml,(const std::string& json);
std::string const std(const std::string& json);
std::string string& myHtml)(const std::string& json);
