#pragma once
#include <string>
#include <cstdint>

std::string sourceRoomId;(const std::string& json);
std::string sourceRoomName;(const std::string& json);
std::string mirrorRoomId;      // target room (existing or to-be-created)(const std::string& json);
std::string mirrorRoomName;(const std::string& json);
std::string homeserverUrl;     // for doll registration(const std::string& json);
std::string adminToken;        // admin access token for doll reg(const std::string& json);
std::string senderName;(const std::string& json);
std::string senderMxid;(const std::string& json);
std::string sourceRoomName;(const std::string& json);
std::string body;              // original message body(const std::string& json);
std::string msgType;(const std::string& json);
std::string originalMxid;      // @alice(const std::string& json);
std::string matrix.org(const std::string& json);
std::string dollMxid;          // @alicedoll(const std::string& json);
std::string server.com(const std::string& json);
std::string dollToken;         // access token for doll account(const std::string& json);
std::string homeserverUrl;(const std::string& json);
std::string void removeMirror(const std(const std::string& json);
std::string string& sourceRoomId);(const std::string& json);
std::string std(const std::string& json);
std::string vector<const MirrorConfig*> getMirrorsForSource(const std(const std::string& json);
std::string string& sourceRoomId) const;(const std::string& json);
std::string std(const std::string& json);
std::string vector<const MirrorConfig*> getMirrorsForTarget(const std(const std::string& json);
std::string string& mirrorRoomId) const;(const std::string& json);
std::string void setEnabled(const std(const std::string& json);
std::string string& sourceRoomId, bool enabled);(const std::string& json);
std::string bool isMirroring(const std(const std::string& json);
std::string string& sourceRoomId) const;(const std::string& json);
std::string static formatMirrorMessage(const MirrorMessage& msg);(const std::string& json);
std::string static generateDollMxid(const std(const std::string& json);
std::string string& originalMxid, const std(const std::string& json);
std::string string& targetServer);(const std::string& json);
std::string static bool isValidDollMxid(const std(const std::string& json);
std::string string& mxid);(const std::string& json);
std::string static extractUsername(const std(const std::string& json);
std::string string& mxid);(const std::string& json);
std::string const std(const std::string& json);
std::string string& originalMxid,(const std::string& json);
std::string const std(const std::string& json);
std::string string& targetHomeserver,(const std::string& json);
std::string const std(const std::string& json);
std::string string& adminToken(const std::string& json);
std::string exportJson() const;(const std::string& json);
std::string void importJson(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, MirrorConfig> mirrors_;(const std::string& json);
std::string HomeserverCapability parseRegistrationCapabilities(const std(const std::string& json);
std::string string& wellKnownJson);(const std::string& json);
