#pragma once
#include <string>
#include <cstdint>

std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int> events;  // event_type → power(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int> users;   // user_id → power(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int> notifications; // notification_key → power(const std::string& json);
std::string void setUserPower(const std(const std::string& json);
std::string string& userId, int powerLevel);(const std::string& json);
std::string int getUserPower(const std(const std::string& json);
std::string string& userId) const;(const std::string& json);
std::string int notificationLevel(const std(const std::string& json);
std::string string& key) const;(const std::string& json);
std::string RoomRole getUserRole(const std(const std::string& json);
std::string string& userId) const;(const std::string& json);
std::string bool canSendEvent(int userPowerLevel, const std(const std::string& json);
std::string string& eventType) const;(const std::string& json);
std::string PowerLevelsContent parsePowerLevels(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string buildPowerLevelsContent(const PowerLevelsContent& pl);(const std::string& json);
std::string void setUserPower(const std(const std::string& json);
std::string string& userId, int powerLevel);(const std::string& json);
std::string getRoleLabel(RoomRole role) const;(const std::string& json);
std::string getRoleLabel(int powerLevel) const;(const std::string& json);
std::string getPowerDescription(int powerLevel) const;(const std::string& json);
std::string formatPowerLevelChange(const std(const std::string& json);
std::string string& userId,(const std::string& json);
std::string buildKickRequest(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& reason = "");(const std::string& json);
std::string buildBanRequest(const std(const std::string& json);
std::string string& userId, const std(const std::string& json);
std::string string& reason = "");(const std::string& json);
std::string buildInviteRequest(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string buildUnbanRequest(const std(const std::string& json);
std::string string& userId);(const std::string& json);
std::string powerLevelsToJson(const PowerLevelsContent& pl) const;(const std::string& json);
std::string roleToJson(const std(const std::string& json);
std::string string& userId, int powerLevel) const;(const std::string& json);
std::string static extractStr(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
std::string static int extractInt(const std(const std::string& json);
std::string string& json, const std(const std::string& json);
std::string string& key);(const std::string& json);
