#pragma once
#include <string>
#include <cstdint>

std::string Membership membershipFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string displayName;(const std::string& json);
std::string signedToken;(const std::string& json);
std::string mxId;(const std::string& json);
std::string reason;              // "reason" key — optional kick/ban reason(const std::string& json);
std::string displayName;         // "displayname" key(const std::string& json);
std::string avatarUrl;           // "avatar_url" key(const std::string& json);
std::string unsignedData;        // "unsigned" key — raw JSON(const std::string& json);
std::string safeReason() const {(const std::string& json);
std::string userId;(const std::string& json);
std::string userPresence;        // "online", "unavailable", "offline"(const std::string& json);
std::string displayName;(const std::string& json);
std::string avatarUrl;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int> events;     // "events" key(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, int> users;      // "users" key(const std::string& json);
std::string void setUserPowerLevel(const std(const std::string& json);
std::string string& userId, int powerLevel) {(const std::string& json);
std::string int notificationLevel(const std(const std::string& json);
std::string string& key) const {(const std::string& json);
std::string name;                // "name" key(const std::string& json);
std::string topic;               // "topic" key(const std::string& json);
std::string avatarUrl;           // "url" key — MXC URI(const std::string& json);
std::string canonicalAlias;              // "alias" key(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> alternativeAliases; // "alt_aliases" key(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> aliases;  // "aliases" key(const std::string& json);
std::string RoomJoinRules roomJoinRulesFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string type;        // "m.room_membership"(const std::string& json);
std::string roomId;      // room ID for allowed members(const std::string& json);
std::string RoomHistoryVisibility roomHistoryVisibilityFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string GuestAccess guestAccessFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string algorithm;           // e.g. "m.megolm.v1.aes-sha2"(const std::string& json);
std::string static RoomEncryptionAlgorithm unsupported(const std(const std::string& json);
std::string string& name) {(const std::string& json);
std::string threadId;            // null for main timeline(const std::string& json);
std::string token;(const std::string& json);
std::string signatures;          // Raw JSON object (Any in Kotlin)(const std::string& json);
std::string mxId;(const std::string& json);
std::string RoomVersioningState roomVersioningStateFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string RoomMemberContent parseRoomMemberContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string RoomPowerLevelsContent parsePowerLevelsContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string RoomNameContent parseRoomNameContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string RoomTopicContent parseRoomTopicContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string RoomAvatarContent parseRoomAvatarContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> allowList;  // "allow" key — wildcards supported(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> denyList;   // "deny" key — wildcards supported(const std::string& json);
std::string keyValidityUrl;          // "key_validity_url" key(const std::string& json);
std::string publicKey;               // "public_key" key — base64 ed25519(const std::string& json);
std::string displayName;             // "display_name" key(const std::string& json);
std::string keyValidityUrl;          // "key_validity_url" key(const std::string& json);
std::string publicKey;               // "public_key" key (legacy)(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> aliases;(const std::string& json);
std::string canonicalAlias;(const std::string& json);
std::string name;(const std::string& json);
std::string roomId;(const std::string& json);
std::string topic;(const std::string& json);
std::string avatarUrl;(const std::string& json);
std::string roomType;                // e.g. "m.space"(const std::string& json);
std::string membership;              // e.g. "leave"(const std::string& json);
std::string getPrimaryAlias() const {(const std::string& json);
std::string RoomDirectoryVisibility roomDirectoryVisibilityFromString(const std(const std::string& json);
std::string string& s);(const std::string& json);
std::string name;(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, std(const std::string& json);
std::string string>> tags;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> aliases;(const std::string& json);
std::string canonicalAlias;(const std::string& json);
std::string name;(const std::string& json);
std::string roomId;(const std::string& json);
std::string topic;(const std::string& json);
std::string avatarUrl;(const std::string& json);
std::string getPrimaryAlias() const {(const std::string& json);
std::string nextBatch;               // "next_batch" key(const std::string& json);
std::string prevBatch;               // "prev_batch" key(const std::string& json);
std::string since;                   // pagination token(const std::string& json);
std::string searchTerm;              // "filter.generic_search_term"(const std::string& json);
std::string filter;                  // JNI compat alias for searchTerm(const std::string& json);
std::string thirdPartyInstanceId;(const std::string& json);
std::string regexp;                  // "regexp" key — validation pattern(const std::string& json);
std::string placeholder;             // "placeholder" key — example value(const std::string& json);
std::string desc;                    // "desc" key — human-readable name(const std::string& json);
std::string icon;                    // "icon" key(const std::string& json);
std::string networkId;               // "network_id" key(const std::string& json);
std::string instanceId;              // "instance_id" key(const std::string& json);
std::string botUserId;               // "bot_user_id" key(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> userFields;     // "user_fields" key(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> locationFields; // "location_fields" key(const std::string& json);
std::string icon;                        // "icon" key(const std::string& json);
std::string std(const std::string& json);
std::string unordered_map<std(const std::string& json);
std::string string, FieldType> fieldTypes; // "field_types" key(const std::string& json);
std::string childRoomId;(const std::string& json);
std::string roomType;(const std::string& json);
std::string name;(const std::string& json);
std::string topic;(const std::string& json);
std::string avatarUrl;(const std::string& json);
std::string order;                        // fractional index for sorting(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> viaServers;(const std::string& json);
std::string parentRoomId;(const std::string& json);
std::string canonicalAlias;(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> aliases;(const std::string& json);
std::string parentId;(const std::string& json);
std::string roomSummaryJson;              // RoomSummary serialized(const std::string& json);
std::string std(const std::string& json);
std::string vector<std(const std::string& json);
std::string string> viaServers;(const std::string& json);
std::string roomId;(const std::string& json);
std::string roomSummaryJson;              // RoomSummary serialized(const std::string& json);
std::string createRoomParamsJson;         // CreateRoomParams serialized(const std::string& json);
std::string replacementRoomId;(const std::string& json);
std::string RoomServerAclContent parseRoomServerAclContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string bool wildcardMatch(const std(const std::string& json);
std::string string& pattern, const std(const std::string& json);
std::string string& value);(const std::string& json);
std::string bool isServerAllowed(const std(const std::string& json);
std::string string& serverName, const RoomServerAclContent& acl);(const std::string& json);
std::string RoomThirdPartyInviteContent parseRoomThirdPartyInvite(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string RoomStrippedState parseRoomStrippedState(const std::string& json);
std::string PublicRoom parsePublicRoom(const std::string& json);
std::string PublicRoomsResponse parsePublicRoomsResponse(const std::string& json);
std::string RoomCanonicalAliasContent parseRoomCanonicalAliasContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string RoomJoinRulesContent parseRoomJoinRulesContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string RoomHistoryVisibilityContent parseRoomHistoryVisibilityContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
std::string RoomGuestAccessContent parseRoomGuestAccessContent(const std(const std::string& json);
std::string string& contentJson);(const std::string& json);
